// =============================================================
// PASSGENI — BLOG CONTENT REGISTRY
// =============================================================
// Every blog post is registered here.
// Page template: pages/blog/[slug].js
// Post content:  content/blog/[slug].js
// =============================================================

export const ALL_POSTS = [
  // ─── LAUNCH BATCH ───────────────────────────────────────────
  {
    slug:            "pci-dss-v4-password-changes-explained",
    title:           "PCI-DSS v4.0 Raised the Password Bar. Here's What You Missed.",
    metaTitle:       "PCI-DSS v4.0 Password Changes: 12-Character Minimum and MFA Expansion | PassGeni",
    metaDescription: "PCI-DSS v4.0 increased minimum password length to 12 characters and expanded MFA requirements to all CDE access. What you need to know before your next audit.",
    excerpt:         "The March 2024 deadline passed. If you haven't updated your authentication controls for PCI-DSS v4.0, here is what changed and what auditors will check.",
    category:        "compliance",
    categoryLabel:   "Compliance",
    categoryColor:   "#ffb74d",
    publishedAt:     "2025-01-10",
    readTime:        6,
    featured:        true,
    faq: [
      { q: "What changed in PCI-DSS v4.0 for passwords?", a: "PCI-DSS v4.0 raised minimum password length from 8 to 12 characters and expanded MFA requirements to all CDE access, not just remote access. These changes became mandatory March 31, 2024." },
      { q: "When did PCI-DSS v4.0 become mandatory?", a: "PCI-DSS v4.0 became mandatory on March 31, 2024. All organisations processing card payments must now comply with v4.0 requirements including the 12-character minimum." },
      { q: "Does PCI-DSS v4.0 require MFA for all employees?", a: "Requirement 8.4.2 requires MFA for all access into the cardholder data environment, including on-site access. This is expanded from v3.2.1 which only required MFA for remote access." },
      { q: "How can PassGeni help with PCI-DSS v4.0?", a: "PassGeni's PCI-DSS preset enforces 12-character minimum with required complexity per Requirement 8.3.6. The Policy Generator creates a written password policy meeting PCI-DSS documentation requirements." },
      { q: "What are the penalties for PCI-DSS non-compliance?", a: "Fines of $5,000-$100,000 per month, increased transaction fees, possible suspension of card processing privileges, and mandatory forensic investigations after any breach involving card data." }
    ],
  },
  {
    slug:            "why-password-complexity-rules-backfire",
    title:           "Why Password Complexity Rules Make You Less Secure",
    metaTitle:       "Password Complexity Rules Are Counterproductive — Here's the Research | PassGeni",
    metaDescription: "Mandatory uppercase, lowercase, numbers, and symbols don't improve security. Here's what the research says and what to do instead.",
    excerpt:         "Requiring uppercase, a number, and a symbol teaches users to choose P@ssw0rd. The research on why complexity rules backfire — and what NIST recommends instead.",
    category:        "research",
    categoryLabel:   "Research",
    categoryColor:   "#ce93d8",
    publishedAt:     "2025-01-14",
    readTime:        5,
    featured:        false,
    faq: [
      { q: "Why do complexity rules make passwords weaker?", a: "Complexity rules produce predictable patterns. Users capitalise the first letter, add a number, append a symbol — creating Summer2024! which satisfies complexity rules but is in every cracking dictionary." },
      { q: "What does NIST say about complexity rules?", a: "NIST 800-63B explicitly recommends against mandatory complexity rules, stating they often make passwords harder to choose and easier to predict. NIST recommends length-based policies and breach checking instead." },
      { q: "What should replace complexity rules?", a: "NIST recommends: minimum length (8+ characters, longer is better), checking against breached credential lists, allowing all printable ASCII and Unicode, and no mandatory rotation without compromise evidence." },
      { q: "Are complexity rules required for HIPAA?", a: "HIPAA requires reasonable and appropriate security, not specific complexity rules. NIST 800-63B-aligned policies are considered HIPAA-compliant by most auditors. PassGeni's HIPAA preset uses length-forward generation." },
      { q: "How do I update my password policy away from complexity rules?", a: "Use PassGeni's Policy Generator to create a NIST 800-63B aligned policy emphasising length. The generator produces a written policy you can adopt or customise, with citation to current NIST guidance." }
    ],
  },
  {
    slug:            "announcing-passgeni-v2",
    title:           "PassGeni V2: DNA Score, Compliance Presets, and 6 New Tools",
    metaTitle:       "PassGeni V2 Launch — DNA Score, Compliance Presets, and Free Tools | PassGeni",
    metaDescription: "PassGeni V2 launches with a new DNA Score system, 6 compliance presets (HIPAA, PCI-DSS, SOC 2, ISO 27001, NIST, DoD), and 6 free security tools.",
    excerpt:         "After months of building, PassGeni V2 is live. Here is everything that's new: DNA Score, compliance presets, post-quantum mode, and 6 standalone security tools.",
    category:        "product",
    categoryLabel:   "Product",
    categoryColor:   "#C8FF00",
    publishedAt:     "2025-01-15",
    readTime:        4,
    featured:        true,
    faq: [],
  },
  // ─── PLACEHOLDERS FOR FUTURE POSTS ─────────────────────────
  // Add new posts here — format above
];

// ─── HELPERS ─────────────────────────────────────────────────

export function getPostBySlug(slug) {
  return ALL_POSTS.find((p) => p.slug === slug) || null;
}

export function getFeaturedPosts() {
  return ALL_POSTS.filter((p) => p.featured);
}

export function getPostsByCategory(category) {
  return ALL_POSTS.filter((p) => p.category === category);
}

export function getRecentPosts(n = 5) {
  return [...ALL_POSTS]
    .sort((a, b) => new Date(b.publishedAt) - new Date(a.publishedAt))
    .slice(0, n);
}

export function getRelatedPosts(slug, n = 3) {
  const post    = getPostBySlug(slug);
  if (!post) return [];
  return ALL_POSTS
    .filter((p) => p.slug !== slug && p.category === post.category)
    .slice(0, n);
}

// ─── BATCH 2 — 25 NEW POSTS ─────────────────────────────────
const BATCH2 = [
  {
    slug: "password-manager-vs-browser-saved-passwords",
    title: "Password Manager vs Browser-Saved Passwords: Which Is Actually Safer?",
    metaTitle: "Password Manager vs Browser Saved Passwords — Which Is Safer? | PassGeni",
    metaDescription: "Browser saved passwords vs dedicated password managers: a real security comparison. Encryption, sync risks, master password protection, and which to use.",
    excerpt: "Chrome and Safari will save your passwords for free. A password manager costs $3/month. Here is the actual security difference — and when the free option is good enough.",
    category: "security",
    categoryLabel: "Security",
    categoryColor: "#64b5f6",
    publishedAt: "2025-02-05",
    readTime: 6,
    featured: false,
    faq: [],
  },
  {
    slug: "how-long-to-crack-my-password",
    title: "How Long Would It Actually Take to Crack Your Password?",
    metaTitle: "How Long to Crack a Password — Real Numbers | PassGeni",
    metaDescription: "Real crack time estimates for different password types. Modern GPU rigs, hashcat, and what 'unbreakable' actually means in practice.",
    excerpt: "A modern GPU rig can test 100 billion MD5 hashes per second. Here is what that means for your actual passwords — and the number that matters most.",
    category: "research",
    categoryLabel: "Research",
    categoryColor: "#ce93d8",
    publishedAt: "2025-02-08",
    readTime: 7,
    featured: false,
    faq: [],
  },
  {
    slug: "2fa-vs-strong-password",
    title: "2FA vs a Strong Password: Which Protects You More?",
    metaTitle: "2FA vs Strong Password — Which Matters More? | PassGeni",
    metaDescription: "Do you need a strong password if you have 2FA? Do you need 2FA if your password is unbreakable? The security tradeoffs explained.",
    excerpt: "Security people argue about this constantly. Here is the honest answer: both matter, but for different attack vectors. Here is how to think about it.",
    category: "security",
    categoryLabel: "Security",
    categoryColor: "#64b5f6",
    publishedAt: "2025-02-12",
    readTime: 5,
    featured: false,
    faq: [],
  },
  {
    slug: "what-is-credential-stuffing",
    title: "What Is Credential Stuffing and Why Your 'Unique' Password Matters",
    metaTitle: "What Is Credential Stuffing? How to Stop It | PassGeni",
    metaDescription: "Credential stuffing attacks use billions of leaked username/password pairs. What it is, how attackers run it, and the only real defense.",
    excerpt: "Attackers bought 3.2 billion username/password pairs from previous breaches and are testing them on every major site right now. Here is exactly how this works.",
    category: "security",
    categoryLabel: "Security",
    categoryColor: "#64b5f6",
    publishedAt: "2025-02-15",
    readTime: 6,
    featured: false,
    faq: [],
  },
  {
    slug: "nist-password-guidelines-2025",
    title: "NIST Password Guidelines 2025: What Changed and What It Means for You",
    metaTitle: "NIST Password Guidelines 2025 — Full Summary | PassGeni",
    metaDescription: "NIST SP 800-63B-4 changes in 2025: no more mandatory rotation, length over complexity, breach-checking requirements. Full practical summary.",
    excerpt: "NIST dropped mandatory rotation, stopped requiring uppercase+symbol combinations, and made length the primary measure of strength. Here is what the 2025 guidelines actually say.",
    category: "compliance",
    categoryLabel: "Compliance",
    categoryColor: "#ffb74d",
    publishedAt: "2025-02-19",
    readTime: 8,
    featured: true,
    faq: [],
  },
  {
    slug: "password-security-for-remote-teams",
    title: "Password Security for Remote Teams: The Gaps Nobody Talks About",
    metaTitle: "Password Security for Remote Teams — Practical Guide | PassGeni",
    metaDescription: "Remote teams create password security gaps that office policies never covered. Shared accounts, personal devices, Slack password-sharing. Here is how to fix it.",
    excerpt: "Your password policy was written for an office. Remote work broke every assumption it made. Here are the five gaps that actually cause breaches in remote-first teams.",
    category: "teams",
    categoryLabel: "Teams",
    categoryColor: "#81c784",
    publishedAt: "2025-02-22",
    readTime: 7,
    featured: false,
    faq: [],
  },
  {
    slug: "are-passphrases-secure-in-2025",
    title: "Are Passphrases Still Secure in 2025? The Updated Math",
    metaTitle: "Are Passphrases Secure in 2025? Entropy Analysis | PassGeni",
    metaDescription: "Are passphrases like 'correct horse battery staple' still secure in 2025? Updated entropy analysis, dictionary attack resistance, and when passphrases fail.",
    excerpt: "The famous XKCD passphrase is 20 years old. Dictionary attacks have evolved. Here is the updated entropy math and when four words is and isn't enough.",
    category: "research",
    categoryLabel: "Research",
    categoryColor: "#ce93d8",
    publishedAt: "2025-02-26",
    readTime: 6,
    featured: false,
    faq: [],
  },
  {
    slug: "biggest-data-breaches-2024-password-lessons",
    title: "The Biggest Data Breaches of 2024 and What They Teach Us About Passwords",
    metaTitle: "Biggest Data Breaches 2024 — Password Security Lessons | PassGeni",
    metaDescription: "2024's largest breaches dissected for password security lessons. Credential reuse, weak service account passwords, MFA bypass — the common threads.",
    excerpt: "2024 saw some of the largest credential leaks in history. Looking across them, three patterns appear in almost every breach. Here they are.",
    category: "security",
    categoryLabel: "Security",
    categoryColor: "#64b5f6",
    publishedAt: "2025-03-01",
    readTime: 8,
    featured: false,
    faq: [],
  },
  {
    slug: "password-security-for-healthcare-2025",
    title: "Password Security for Healthcare Workers in 2025: Practical, HIPAA-Ready",
    metaTitle: "Password Security for Healthcare Workers 2025 | PassGeni",
    metaDescription: "Healthcare-specific password security: HIPAA requirements, shared workstation challenges, EHR login best practices, and tools that work in clinical environments.",
    excerpt: "Healthcare has some of the tightest password requirements and the most friction-heavy login environments. Here is how to meet HIPAA requirements without slowing down patient care.",
    category: "profession",
    categoryLabel: "Profession",
    categoryColor: "#f48fb1",
    publishedAt: "2025-03-05",
    readTime: 7,
    featured: false,
    faq: [],
  },
  {
    slug: "why-you-should-stop-rotating-passwords",
    title: "Why You Should Stop Rotating Passwords (Unless You're Breached)",
    metaTitle: "Stop Rotating Passwords — NIST Now Agrees | PassGeni",
    metaDescription: "Mandatory password rotation increases security risk. NIST, NCSC, and Microsoft all recommend against it. Here is why, with research to back it up.",
    excerpt: "IT departments have been forcing 90-day password rotations for 20 years. NIST, Microsoft, and the NCSC now say this makes you less secure. Here is the research.",
    category: "research",
    categoryLabel: "Research",
    categoryColor: "#ce93d8",
    publishedAt: "2025-03-08",
    readTime: 5,
    featured: false,
    faq: [],
  },
  {
    slug: "api-key-security-best-practices",
    title: "API Key Security Best Practices: The Complete 2025 Checklist",
    metaTitle: "API Key Security Best Practices 2025 | PassGeni",
    metaDescription: "API key security: generation, storage, rotation, scope restriction, leak detection. Complete checklist for developers handling credentials in code.",
    excerpt: "API keys in .env files get committed to GitHub every day. Here is the complete checklist for generating, storing, rotating, and detecting leaks for API credentials.",
    category: "developer",
    categoryLabel: "Developer",
    categoryColor: "#80cbc4",
    publishedAt: "2025-03-12",
    readTime: 9,
    featured: false,
    faq: [],
  },
  {
    slug: "sso-vs-passwords",
    title: "SSO vs Passwords: When to Use Each and When to Use Both",
    metaTitle: "SSO vs Passwords — When to Use Each | PassGeni",
    metaDescription: "Single sign-on vs traditional passwords: tradeoffs, risks, when SSO creates single points of failure, and when you still need strong standalone passwords.",
    excerpt: "SSO sounds like the answer to password sprawl. And often it is. But SSO also creates single points of failure that attackers specifically target. Here is how to think about it.",
    category: "security",
    categoryLabel: "Security",
    categoryColor: "#64b5f6",
    publishedAt: "2025-03-15",
    readTime: 6,
    featured: false,
    faq: [],
  },
  {
    slug: "password-security-for-accountants",
    title: "Password Security for Accountants: Protecting Client Financial Data",
    metaTitle: "Password Security for Accountants — Client Data Protection | PassGeni",
    metaDescription: "Accountants handle sensitive financial data across multiple clients. Password best practices for QuickBooks, Xero, client portals, and tax software.",
    excerpt: "Accountants manage credentials for client portals, tax software, banking platforms, and their own practice management tools. Here is the practical security setup.",
    category: "profession",
    categoryLabel: "Profession",
    categoryColor: "#f48fb1",
    publishedAt: "2025-03-19",
    readTime: 6,
    featured: false,
    faq: [],
  },
  {
    slug: "how-haveibeenpwned-works",
    title: "How Have I Been Pwned Works — and Why k-Anonymity Matters",
    metaTitle: "How Have I Been Pwned Works — k-Anonymity Explained | PassGeni",
    metaDescription: "How the HIBP breach database works, what k-anonymity means for password checking, how PassGeni uses it safely, and Troy Hunt's architecture explained.",
    excerpt: "Have I Been Pwned checks 12 billion compromised credentials. Here is exactly how it works, what k-anonymity means, and why you can check passwords without revealing them.",
    category: "research",
    categoryLabel: "Research",
    categoryColor: "#ce93d8",
    publishedAt: "2025-03-22",
    readTime: 7,
    featured: false,
    faq: [],
  },
  {
    slug: "building-a-company-password-policy",
    title: "How to Build a Company Password Policy That People Actually Follow",
    metaTitle: "Company Password Policy Guide — One People Follow | PassGeni",
    metaDescription: "Building a password policy that employees actually follow: realistic complexity requirements, tooling, enforcement, and the psychology of compliance.",
    excerpt: "Most company password policies are ignored within a week. Here is how to write one that balances genuine security with the reality that humans have limited patience for friction.",
    category: "teams",
    categoryLabel: "Teams",
    categoryColor: "#81c784",
    publishedAt: "2025-03-26",
    readTime: 8,
    featured: false,
    faq: [],
  },
  {
    slug: "what-makes-a-password-unbreakable",
    title: "What Actually Makes a Password Unbreakable in 2025?",
    metaTitle: "What Makes a Password Unbreakable in 2025? | PassGeni",
    metaDescription: "The specific properties that make a password resistant to modern cracking: entropy thresholds, character pool math, GPU benchmarks, and the PassGeni DNA Score.",
    excerpt: "Unbreakable is a strong word. But there is a specific entropy threshold above which brute force becomes computationally infeasible for any plausible attacker. Here is the number.",
    category: "research",
    categoryLabel: "Research",
    categoryColor: "#ce93d8",
    publishedAt: "2025-04-01",
    readTime: 7,
    featured: false,
    faq: [],
  },
  {
    slug: "password-security-for-ecommerce",
    title: "Password Security for eCommerce Businesses: PCI-DSS Without the Headaches",
    metaTitle: "Password Security for eCommerce — PCI-DSS Guide | PassGeni",
    metaDescription: "eCommerce businesses must meet PCI-DSS password requirements. Practical guide to compliant credentials for Shopify, WooCommerce, and payment systems.",
    excerpt: "Any business that touches card data needs PCI-DSS compliant password controls. Here is what that means for eCommerce operators and how to implement it without a security team.",
    category: "compliance",
    categoryLabel: "Compliance",
    categoryColor: "#ffb74d",
    publishedAt: "2025-04-05",
    readTime: 6,
    featured: false,
    faq: [],
  },
  {
    slug: "the-problem-with-security-questions",
    title: "The Problem With Security Questions (And What to Use Instead)",
    metaTitle: "Why Security Questions Are Insecure — Better Alternatives | PassGeni",
    metaDescription: "Security questions are a security anti-pattern. Why they fail, how attackers bypass them, and what to use for account recovery instead.",
    excerpt: "Your mother's maiden name is on LinkedIn. Your first pet is in a Facebook post from 2009. Security questions are security theater — here is why, and what actually works.",
    category: "security",
    categoryLabel: "Security",
    categoryColor: "#64b5f6",
    publishedAt: "2025-04-09",
    readTime: 5,
    featured: false,
    faq: [],
  },
  {
    slug: "password-security-statistics-2025",
    title: "Password Security Statistics 2025: The Numbers Behind the Risk",
    metaTitle: "Password Security Statistics 2025 — Key Data | PassGeni",
    metaDescription: "2025 password security statistics: breach numbers, reuse rates, cracking benchmarks, enterprise adoption figures, and what the data says about human password behavior.",
    excerpt: "81% of hacking-related breaches involve stolen or weak passwords. Here are the key 2025 statistics on password security — and what they actually mean.",
    category: "research",
    categoryLabel: "Research",
    categoryColor: "#ce93d8",
    publishedAt: "2025-04-14",
    readTime: 6,
    featured: false,
    faq: [],
  },
  {
    slug: "ai-password-cracking-2025",
    title: "AI Password Cracking in 2025: What Large Language Models Changed",
    metaTitle: "AI Password Cracking 2025 — LLMs and Credential Security | PassGeni",
    metaDescription: "How AI and large language models changed password cracking: smarter pattern guessing, PersonGAN, PassGAN, and what it means for your credentials.",
    excerpt: "AI-assisted password cracking isn't about brute force anymore — it's about pattern prediction. Here is what PassGAN, PersonGAN, and LLM-assisted attacks actually do.",
    category: "research",
    categoryLabel: "Research",
    categoryColor: "#ce93d8",
    publishedAt: "2025-04-18",
    readTime: 8,
    featured: true,
    faq: [],
  },
  {
    slug: "password-managers-for-small-business",
    title: "The Best Password Managers for Small Business in 2025",
    metaTitle: "Best Password Managers for Small Business 2025 | PassGeni",
    metaDescription: "Password manager comparison for small businesses: 1Password Teams, Bitwarden Business, Dashlane, Keeper. Features, pricing, and which to choose.",
    excerpt: "Small businesses have different password management needs than individuals or enterprises. Here is the honest comparison for teams of 5 to 50.",
    category: "tools",
    categoryLabel: "Tools",
    categoryColor: "#ffb74d",
    publishedAt: "2025-04-22",
    readTime: 8,
    featured: false,
    faq: [],
  },
  {
    slug: "passkeys-vs-passwords-2025",
    title: "Passkeys vs Passwords in 2025: Is the Password Era Actually Over?",
    metaTitle: "Passkeys vs Passwords 2025 — Is the Password Era Over? | PassGeni",
    metaDescription: "Passkeys are on Apple, Google, and Microsoft. Are passwords obsolete? What passkeys actually are, where they fail, and why strong passwords still matter.",
    excerpt: "Apple, Google, and Microsoft all support passkeys. Major sites are rolling them out. Is the password era over? The honest answer is: not quite yet, and here is why.",
    category: "security",
    categoryLabel: "Security",
    categoryColor: "#64b5f6",
    publishedAt: "2025-04-26",
    readTime: 7,
    featured: true,
    faq: [],
  },
  {
    slug: "password-hygiene-checklist",
    title: "Password Hygiene Checklist: 15 Things to Fix This Weekend",
    metaTitle: "Password Hygiene Checklist — 15 Things to Fix Now | PassGeni",
    metaDescription: "15 actionable password security improvements you can make this weekend. From breach checking to passphrase setup to manager enrollment.",
    excerpt: "15 concrete password security improvements, ordered by impact. Most take under 5 minutes. Do the first five this weekend and you'll have better security than 90% of users.",
    category: "security",
    categoryLabel: "Security",
    categoryColor: "#64b5f6",
    publishedAt: "2025-04-30",
    readTime: 5,
    featured: false,
    faq: [],
  },
  {
    slug: "how-password-hashing-works",
    title: "How Password Hashing Works: bcrypt, Argon2, and What Your App Should Use",
    metaTitle: "Password Hashing: bcrypt vs Argon2 vs scrypt | PassGeni",
    metaDescription: "How password hashing works under the hood: bcrypt, Argon2, scrypt, PBKDF2. Which algorithm to use, what work factor to set, and how to migrate legacy MD5 hashes.",
    excerpt: "Your database stores password hashes, not passwords. Here is how modern hashing algorithms work, why bcrypt is being replaced by Argon2, and what work factor to use in 2025.",
    category: "developer",
    categoryLabel: "Developer",
    categoryColor: "#80cbc4",
    publishedAt: "2025-05-04",
    readTime: 9,
    featured: false,
    faq: [],
  },
  {
    slug: "zero-knowledge-proof-passwords",
    title: "Zero-Knowledge Proofs and Passwords: What 'Zero-Knowledge' Actually Means",
    metaTitle: "Zero-Knowledge Proofs for Passwords Explained | PassGeni",
    metaDescription: "Zero-knowledge proofs in password security: SRP protocol, ZKP authentication, how PassGeni's zero-knowledge architecture works, and what it actually guarantees.",
    excerpt: "Zero-knowledge is used as a marketing term by dozens of tools. Here is what it actually means mathematically, how it applies to password security, and how to verify a tool's claims.",
    category: "research",
    categoryLabel: "Research",
    categoryColor: "#ce93d8",
    publishedAt: "2025-05-08",
    readTime: 10,
    featured: false,
    faq: [],
  },
];

// Merge into ALL_POSTS
ALL_POSTS.push(...BATCH2);

// ─── BATCH 3 — 25 NEW POSTS ────────────────────────────────────
const BATCH3 = [
  {
    slug: "best-password-manager-2025",
    title: "The Best Password Managers in 2025: An Honest Comparison",
    metaTitle: "Best Password Managers 2025 — Honest Comparison | PassGeni",
    metaDescription: "1Password vs Bitwarden vs Dashlane vs Keeper in 2025. Pricing, security architecture, zero-knowledge claims, and which one to actually use.",
    excerpt: "1Password, Bitwarden, Dashlane, Keeper, NordPass — reviewed honestly. Security architecture, pricing, and which one you should actually use.",
    category: "tools", categoryLabel: "Tools", categoryColor: "#80cbc4",
    publishedAt: "2025-06-01", readTime: 10, featured: true,
  },
  {
    slug: "password-spraying-attack-explained",
    title: "Password Spraying Attacks: What They Are and How to Stop Them",
    metaTitle: "Password Spraying Attacks Explained — How to Prevent Them | PassGeni",
    metaDescription: "Password spraying attacks test one common password against thousands of accounts. How they work, why traditional lockout policies miss them, and how to defend.",
    excerpt: "A password spray attack tries one common password — 'Spring2025!' — against every account in a directory. Here's how they work and how to stop them.",
    category: "security", categoryLabel: "Security", categoryColor: "#f48fb1",
    publishedAt: "2025-06-03", readTime: 7, featured: false,
  },
  {
    slug: "how-to-audit-your-passwords",
    title: "How to Audit All Your Passwords in 30 Minutes",
    metaTitle: "How to Audit Your Passwords in 30 Minutes | PassGeni",
    metaDescription: "A step-by-step password audit process: breach checking, entropy scoring, duplicate detection, and prioritising which accounts to fix first.",
    excerpt: "Most people have at least 3 compromised passwords and don't know it. Here's a 30-minute process to audit everything and fix the worst ones first.",
    category: "howto", categoryLabel: "How-To", categoryColor: "#C8FF00",
    publishedAt: "2025-06-05", readTime: 6, featured: false,
  },
  {
    slug: "why-sms-2fa-is-not-enough",
    title: "Why SMS Two-Factor Authentication Is Not Enough in 2025",
    metaTitle: "Why SMS 2FA Is Insecure — SIM Swapping & SS7 Explained | PassGeni",
    metaDescription: "SMS 2FA is better than nothing but vulnerable to SIM swapping, SS7 attacks, and SIM cloning. Why TOTP apps and hardware keys are the right upgrade.",
    excerpt: "SMS 2FA is better than no 2FA. But SIM swapping attacks, SS7 vulnerabilities, and real-time phishing make it the weakest layer. Here's what to use instead.",
    category: "security", categoryLabel: "Security", categoryColor: "#f48fb1",
    publishedAt: "2025-06-07", readTime: 8, featured: false,
  },
  {
    slug: "gdpr-password-requirements",
    title: "GDPR Password Requirements: What Article 32 Actually Demands",
    metaTitle: "GDPR Password Requirements — Article 32 Explained | PassGeni",
    metaDescription: "GDPR Article 32 requires 'appropriate technical measures' for authentication. What that means for password policies, breach notification, and encryption standards.",
    excerpt: "GDPR doesn't specify a minimum password length — but it does require 'appropriate' security. What that means practically for EU businesses and their password policies.",
    category: "compliance", categoryLabel: "Compliance", categoryColor: "#ffb74d",
    publishedAt: "2025-06-09", readTime: 7, featured: false,
  },
  {
    slug: "password-reuse-statistics",
    title: "Password Reuse Is Still Everywhere: The 2025 Data",
    metaTitle: "Password Reuse Statistics 2025 — The Data on Credential Recycling | PassGeni",
    metaDescription: "65% of people reuse passwords across multiple sites. The data on password reuse, why credential stuffing works, and what actually changes behaviour.",
    excerpt: "Studies consistently show 60–65% of people reuse passwords across sites. Here's the latest data, why it hasn't improved, and what interventions actually work.",
    category: "research", categoryLabel: "Research", categoryColor: "#ce93d8",
    publishedAt: "2025-06-11", readTime: 6, featured: false,
  },
  {
    slug: "secure-password-sharing-teams",
    title: "How to Share Passwords Securely Across a Team",
    metaTitle: "Secure Password Sharing for Teams — Best Practices 2025 | PassGeni",
    metaDescription: "Sharing passwords via Slack, email, or WhatsApp exposes your team to credential theft. The secure alternatives: shared vaults, encrypted links, and zero-knowledge tools.",
    excerpt: "Texting a password to a colleague seems harmless. It isn't. Here's how teams should share credentials securely — from one-time links to shared vaults.",
    category: "howto", categoryLabel: "How-To", categoryColor: "#C8FF00",
    publishedAt: "2025-06-13", readTime: 7, featured: false,
  },
  {
    slug: "ai-generated-passwords-security",
    title: "Are AI-Generated Passwords Actually Secure?",
    metaTitle: "AI-Generated Passwords: Are They Actually Secure? | PassGeni",
    metaDescription: "ChatGPT and other LLMs can suggest passwords but shouldn't generate them for security use. Why LLM entropy is fundamentally different from cryptographic randomness.",
    excerpt: "LLMs like ChatGPT can suggest passwords that look random but aren't. Here's why true cryptographic randomness and AI-generated text are completely different things.",
    category: "research", categoryLabel: "Research", categoryColor: "#ce93d8",
    publishedAt: "2025-06-15", readTime: 8, featured: false,
  },
  {
    slug: "password-security-for-fintech",
    title: "Password Security for Fintech: PCI-DSS, Open Banking, and API Keys",
    metaTitle: "Password Security for Fintech Companies — PCI-DSS & API Keys | PassGeni",
    metaDescription: "Fintech-specific password security: PCI-DSS v4.0 requirements, Open Banking API credential management, service account security, and developer key rotation.",
    excerpt: "Fintech companies carry PCI-DSS obligations, manage customer banking credentials, and run API ecosystems. Here's what password security means in that context.",
    category: "compliance", categoryLabel: "Compliance", categoryColor: "#ffb74d",
    publishedAt: "2025-06-17", readTime: 9, featured: false,
  },
  {
    slug: "hardware-security-keys-explained",
    title: "Hardware Security Keys Explained: YubiKey, Titan, and FIDO2",
    metaTitle: "Hardware Security Keys — YubiKey vs Google Titan vs FIDO2 | PassGeni",
    metaDescription: "Hardware security keys eliminate phishing for strong accounts. How FIDO2 works, YubiKey vs Google Titan comparison, and when to use a hardware key vs TOTP.",
    excerpt: "A hardware key makes phishing technically impossible for the accounts it protects. How FIDO2 works, which key to buy, and when passwords still matter alongside them.",
    category: "security", categoryLabel: "Security", categoryColor: "#f48fb1",
    publishedAt: "2025-06-19", readTime: 8, featured: false,
  },
  {
    slug: "brute-force-attack-how-long",
    title: "How Long Would It Take to Brute-Force Your Password in 2025?",
    metaTitle: "Brute Force Attack Time — How Long to Crack Your Password 2025 | PassGeni",
    metaDescription: "With modern GPUs, an 8-character password can be cracked in under an hour. The actual brute-force timelines for different password lengths, character sets, and hashing algorithms.",
    excerpt: "An 8-character password against modern GPU cracking rigs: under an hour for MD5, under a day for bcrypt. Here are the real timelines based on current hardware.",
    category: "research", categoryLabel: "Research", categoryColor: "#ce93d8",
    publishedAt: "2025-06-21", readTime: 7, featured: false,
  },
  {
    slug: "password-security-for-nonprofits",
    title: "Password Security for Nonprofits: Budget-Friendly and Compliant",
    metaTitle: "Password Security for Nonprofits — Free and Budget Tools 2025 | PassGeni",
    metaDescription: "Nonprofits face the same credential threats as enterprises but with smaller budgets. Free and low-cost password security tools, donor data protection, and volunteer account management.",
    excerpt: "Nonprofits are increasingly targeted because security is often an afterthought. Here's how to protect donor data and staff accounts on a limited budget.",
    category: "howto", categoryLabel: "How-To", categoryColor: "#C8FF00",
    publishedAt: "2025-06-23", readTime: 6, featured: false,
  },
  {
    slug: "multi-factor-authentication-guide",
    title: "Multi-Factor Authentication: The Complete Setup Guide for 2025",
    metaTitle: "Multi-Factor Authentication Setup Guide 2025 | PassGeni",
    metaDescription: "A practical MFA setup guide: TOTP apps (Authy, Google Authenticator), hardware keys, recovery codes, and which accounts to prioritise for MFA first.",
    excerpt: "MFA stops 99.9% of automated account takeovers. Here's how to set it up correctly — which app to use, how to store recovery codes, and which accounts to prioritise.",
    category: "howto", categoryLabel: "How-To", categoryColor: "#C8FF00",
    publishedAt: "2025-06-25", readTime: 8, featured: false,
  },
  {
    slug: "password-security-for-education",
    title: "Password Security in Education: K-12 and Higher Ed Guide",
    metaTitle: "Password Security for Schools and Universities 2025 | PassGeni",
    metaDescription: "FERPA compliance, student data protection, and practical password policies for K-12 and higher education institutions.",
    excerpt: "Schools manage student PII under FERPA, often with users aged 13–22 who have terrible password habits. Here's a practical framework for education institutions.",
    category: "compliance", categoryLabel: "Compliance", categoryColor: "#ffb74d",
    publishedAt: "2025-06-27", readTime: 7, featured: false,
  },
  {
    slug: "what-is-credential-stuffing-prevention",
    title: "Credential Stuffing Prevention: What Actually Works in 2025",
    metaTitle: "Credential Stuffing Prevention — What Actually Works | PassGeni",
    metaDescription: "Credential stuffing uses leaked username/password combos to break into accounts. Rate limiting, CAPTCHA, breach detection, and MFA — what works and what doesn't.",
    excerpt: "After every major data breach, attackers try those credentials everywhere. Here's what actually works to stop credential stuffing — and what just creates friction.",
    category: "security", categoryLabel: "Security", categoryColor: "#f48fb1",
    publishedAt: "2025-06-29", readTime: 8, featured: false,
  },
  {
    slug: "passphrase-generator-guide",
    title: "How to Use a Passphrase Generator: The NIST 800-63B Guide",
    metaTitle: "Passphrase Generator Guide — NIST 800-63B Explained | PassGeni",
    metaDescription: "How to generate NIST-recommended passphrases: word count, entropy math, separator choices, and why four random words beat any 8-character complex password.",
    excerpt: "Four random words from a large dictionary gives you 50+ bits of entropy and something you can actually remember. Here's how to generate one and why it works.",
    category: "howto", categoryLabel: "How-To", categoryColor: "#C8FF00",
    publishedAt: "2025-07-01", readTime: 5, featured: false,
  },
  {
    slug: "password-security-for-marketers",
    title: "Password Security for Marketing Teams: Shared Accounts and Agency Access",
    metaTitle: "Password Security for Marketers — Shared Accounts & Agency Access | PassGeni",
    metaDescription: "Marketing teams share social media, analytics, and ad platform credentials constantly. How to do it securely without losing access when someone leaves.",
    excerpt: "Marketing teams are among the worst for password security — shared logins, agency handoffs, and social accounts with no MFA. Here's how to fix that.",
    category: "howto", categoryLabel: "How-To", categoryColor: "#C8FF00",
    publishedAt: "2025-07-03", readTime: 6, featured: false,
  },
  {
    slug: "what-happens-after-data-breach",
    title: "What Actually Happens After a Data Breach: A Timeline",
    metaTitle: "What Happens After a Data Breach — Timeline & Response | PassGeni",
    metaDescription: "From breach occurrence to dark web sale to account takeover: the actual timeline of a data breach and what you should do at each stage.",
    excerpt: "A data breach doesn't become an account takeover the next day. Here's the actual timeline — from when data is stolen to when it shows up in credential stuffing attacks.",
    category: "security", categoryLabel: "Security", categoryColor: "#f48fb1",
    publishedAt: "2025-07-05", readTime: 7, featured: false,
  },
  {
    slug: "password-length-vs-complexity",
    title: "Password Length vs Complexity: Which Actually Matters More?",
    metaTitle: "Password Length vs Complexity — The Entropy Math | PassGeni",
    metaDescription: "A 20-character lowercase password has more entropy than a 10-character complex one. The entropy math on length vs character set size, with real examples.",
    excerpt: "Length wins. A 20-character lowercase password beats a 10-character one with symbols, every time. Here's the entropy math that proves it.",
    category: "research", categoryLabel: "Research", categoryColor: "#ce93d8",
    publishedAt: "2025-07-07", readTime: 6, featured: false,
  },
  {
    slug: "api-security-best-practices-2025",
    title: "API Security Best Practices in 2025: Keys, Tokens, and Secrets",
    metaTitle: "API Security Best Practices 2025 — Keys, Tokens & Secrets | PassGeni",
    metaDescription: "API key management, token rotation, secret scanning, and vault strategies for development teams in 2025. What leaked API keys cost and how to prevent it.",
    excerpt: "API keys in GitHub repos caused $1M+ in cloud charges for companies last year. Here's how to manage secrets correctly — rotation, vaults, scanning, and expiry.",
    category: "developer", categoryLabel: "Developer", categoryColor: "#80cbc4",
    publishedAt: "2025-07-09", readTime: 9, featured: false,
  },
  {
    slug: "password-security-myths-debunked",
    title: "10 Password Security Myths Still Circulating in 2025",
    metaTitle: "10 Password Security Myths Debunked in 2025 | PassGeni",
    metaDescription: "From 'change your password every 90 days' to 'symbols make passwords stronger' — the most persistent password myths, debunked with current research.",
    excerpt: "Mandatory rotation, complexity rules, security questions — most mainstream password advice is outdated. Here are 10 myths still being enforced in corporate IT.",
    category: "research", categoryLabel: "Research", categoryColor: "#ce93d8",
    publishedAt: "2025-07-11", readTime: 7, featured: false,
  },
  {
    slug: "password-security-remote-work-2025",
    title: "Password Security for Remote Work in 2025: The Threat Landscape Has Changed",
    metaTitle: "Password Security for Remote Work 2025 | PassGeni",
    metaDescription: "Home networks, personal devices, and VPN fatigue have changed the remote work threat landscape since 2020. Updated password and access security practices for distributed teams.",
    excerpt: "Five years after the mass shift to remote work, the security posture of most distributed teams still hasn't caught up. Here's what actually needs to change.",
    category: "security", categoryLabel: "Security", categoryColor: "#f48fb1",
    publishedAt: "2025-07-13", readTime: 8, featured: false,
  },
  {
    slug: "open-source-password-managers",
    title: "Open Source Password Managers: Bitwarden, KeePass, and Vaultwarden Reviewed",
    metaTitle: "Open Source Password Managers 2025 — Bitwarden vs KeePass | PassGeni",
    metaDescription: "Bitwarden, KeePass, Vaultwarden, and Passbolt reviewed: self-hosting options, audit history, mobile apps, and when open source is the right choice.",
    excerpt: "Open source password managers give you something closed-source tools can't: verifiable code. Here's how Bitwarden, KeePass, and Vaultwarden compare in 2025.",
    category: "tools", categoryLabel: "Tools", categoryColor: "#80cbc4",
    publishedAt: "2025-07-15", readTime: 8, featured: false,
  },
  {
    slug: "enterprise-password-policy-template",
    title: "Enterprise Password Policy Template: Copy-Paste and Customise",
    metaTitle: "Enterprise Password Policy Template 2025 — Free Download | PassGeni",
    metaDescription: "A complete enterprise password policy template covering NIST 800-63B, SOC 2, and ISO 27001 requirements. Ready to customise for your organisation.",
    excerpt: "Most companies don't have a written password policy. Here's a complete template you can adapt — covering NIST, SOC 2, and ISO 27001 in plain language.",
    category: "compliance", categoryLabel: "Compliance", categoryColor: "#ffb74d",
    publishedAt: "2025-07-17", readTime: 8, featured: false,
  },
  {
    slug: "dictionary-attack-vs-brute-force",
    title: "Dictionary Attack vs Brute Force: What's the Difference?",
    metaTitle: "Dictionary Attack vs Brute Force Attack Explained | PassGeni",
    metaDescription: "Dictionary attacks and brute force attacks work differently and defeat different defences. Understanding the distinction helps you choose the right password strategy.",
    excerpt: "Dictionary attacks and brute force attacks are not the same thing. The distinction matters for how you build passwords that resist each type of attack.",
    category: "security", categoryLabel: "Security", categoryColor: "#f48fb1",
    publishedAt: "2025-07-19", readTime: 6, featured: false,
  },
];

ALL_POSTS.push(...BATCH3);
