// =============================================================
// PASSGENI — GUIDES CONTENT REGISTRY
// =============================================================
// Every guide lives here. Add a new guide by adding one object.
// The page template at pages/guides/[slug].js handles rendering.
// Writing the full guide content goes in content/guides/[slug].js
// =============================================================

// ─── TIER 1: COMPLIANCE GUIDES ───────────────────────────────
export const COMPLIANCE_GUIDES = [
  {
    slug:            "hipaa-password-requirements",
    title:           "HIPAA Password Requirements: The Complete 2025 Guide",
    metaTitle:       "HIPAA Password Requirements 2025 — What You Actually Need | PassGeni",
    metaDescription: "Exact HIPAA password requirements for 2025: minimum length, complexity, rotation, MFA, and audit controls. Includes a ready-to-use policy template.",
    excerpt:         "What HIPAA actually requires for passwords, what it recommends, and how to implement compliant controls without crippling your staff.",
    tier:            1,
    badge:           "HIPAA",
    badgeColor:      "#4fc3f7",
    publishedAt:     "2025-01-15",
    updatedAt:       "2025-01-15",
    readTime:        12,
    faq: [
      { q: "What is the minimum password length required by HIPAA?", a: "HIPAA does not specify an exact minimum length in its text. However, HHS guidance and NIST recommendations used as the security standard require at least 8 characters, with 12+ as best practice." },
      { q: "Does HIPAA require password rotation?", a: "HIPAA requires 'automatic logoff' and periodic review of access, which is broadly interpreted to include rotation. Best practice under HIPAA is 90-day rotation for most accounts, though NIST now questions mandatory rotation." },
      { q: "Is MFA required under HIPAA?", a: "MFA is not explicitly required by HIPAA, but it is strongly recommended and increasingly considered best practice for ePHI access, especially remote access." },
,
      { q: "Does HIPAA specify a minimum password length?", a: "HIPAA's Security Rule does not specify an exact minimum. HHS guidance and NIST 800-63B (used as the de facto standard) recommend 12 characters minimum. OCR breach investigations frequently cite short passwords as evidence of inadequate access controls." },
      { q: "Is multi-factor authentication required for HIPAA?", a: "MFA is not explicitly mandated in the HIPAA Security Rule text, but is strongly recommended and increasingly expected. OCR's guidance and recent enforcement actions treat MFA absence as evidence of inadequate access controls, especially for remote ePHI access." },
      { q: "How often must HIPAA passwords be changed?", a: "HIPAA does not mandate a specific rotation schedule. NIST 800-63B, used as HIPAA's security reference, explicitly recommends against mandatory rotation. Change passwords only when compromise is suspected or confirmed." },
      { q: "What password policy does HIPAA require to be documented?", a: "HIPAA requires written policies and procedures under 45 CFR 164.308(a)(5)(ii)(D). Your written password policy must cover minimum length, complexity requirements, change procedures, and access controls. Use PassGeni's Policy Generator to create a compliant document." },
      { q: "Can healthcare organisations use passphrases for HIPAA?", a: "Yes. Passphrases fully satisfy HIPAA requirements and are NIST-recommended. A 4-word passphrase with 16+ characters exceeds length requirements and is more memorable for clinical staff, reducing insecure workarounds like writing passwords on sticky notes." },
      { q: "What happens if HIPAA password requirements are violated?", a: "OCR fines range from $100 to $50,000 per violation category, with annual caps up to $1.9 million. OCR has levied fines specifically for authentication failures. Shared passwords and missing MFA have both featured in enforcement settlements." },
      { q: "Does HIPAA apply to password managers?", a: "Using a password manager for ePHI system credentials is generally acceptable and encouraged under HIPAA. Ensure the password manager itself has strong encryption, MFA, and a zero-knowledge architecture. Cloud-based managers should be covered by a Business Associate Agreement if they could theoretically access ePHI." }
    ],
  },
  {
    slug:            "pci-dss-password-requirements",
    title:           "PCI-DSS v4.0 Password Requirements: What Changed in 2024",
    metaTitle:       "PCI-DSS v4.0 Password Requirements 2024 — Complete Guide | PassGeni",
    metaDescription: "PCI-DSS v4.0 raised minimum password length to 12 characters. Full breakdown of what changed, what stayed the same, and how to implement compliant controls.",
    excerpt:         "PCI-DSS v4.0 made significant changes to password requirements. Here is exactly what changed, what stayed the same, and how to get compliant.",
    tier:            1,
    badge:           "PCI-DSS",
    badgeColor:      "#ffb74d",
    publishedAt:     "2025-01-20",
    updatedAt:       "2025-01-20",
    readTime:        10,
    faq: [
      { q: "What changed in PCI-DSS v4.0 for passwords?", a: "The minimum password length increased from 7 to 12 characters. MFA requirements were expanded. The timeline for compliance was March 2025." },
      { q: "Does PCI-DSS v4.0 require MFA?", a: "Yes. PCI-DSS v4.0 Requirement 8.4 requires MFA for all non-console access into the cardholder data environment, and for all remote network access." },
,
      { q: "What is the minimum password length for PCI-DSS v4.0?", a: "PCI-DSS v4.0 Requirement 8.3.6 requires a minimum of 12 characters for user passwords accessing the cardholder data environment. This increased from 8 characters in v3.2.1 and became mandatory March 31, 2024." },
      { q: "Does PCI-DSS v4.0 require MFA for everyone?", a: "PCI-DSS v4.0 Requirement 8.4.2 requires MFA for all access to the cardholder data environment, including on-site non-console access. Previously, MFA was only required for remote access. This is one of the most significant changes in v4.0." },
      { q: "How often must passwords be changed under PCI-DSS?", a: "PCI-DSS v4.0 no longer mandates automatic periodic password rotation. Instead, Requirement 8.3.9 requires passwords to be changed when compromise is suspected. This aligns with NIST 800-63B's evidence-based rotation approach." },
      { q: "What are the PCI-DSS password complexity requirements?", a: "Requirement 8.3.6 requires passwords to contain characters from at least three of the four categories: uppercase letters, lowercase letters, digits, and special characters. Passwords must be a minimum of 12 characters." },
      { q: "Does PCI-DSS apply to service account passwords?", a: "Yes. All system-level accounts, service accounts, and application accounts with CDE access must comply with PCI-DSS password requirements. Shared generic accounts are prohibited — all CDE access must be individual and auditable per Requirement 8.2.2." },
      { q: "What is the penalty for PCI-DSS password non-compliance?", a: "Card brands can impose fines of $5,000–$100,000 per month on acquiring banks, who pass costs to merchants. After a breach, non-compliant organisations face forensic investigation costs, increased transaction fees, and potential loss of card processing privileges." },
      { q: "How does PassGeni enforce PCI-DSS v4.0 compliance?", a: "PassGeni's PCI-DSS preset automatically enforces Requirement 8.3.6: 12-character minimum, uppercase, lowercase, and either digit or symbol required. The Policy Generator produces a written password policy citing specific PCI-DSS requirement numbers for audit documentation." },
      { q: "Can passphrases satisfy PCI-DSS requirements?", a: "Yes, if they meet minimum character requirements. A 4-word passphrase of 16+ characters satisfies the 12-character minimum. Add a number or symbol to satisfy the character diversity requirement. PassGeni's passphrase mode with PCI-DSS preset enforces this automatically." }
    ],
  },
  {
    slug:            "soc2-password-requirements",
    title:           "SOC 2 Password Requirements: CC6.1 Explained",
    metaTitle:       "SOC 2 Password Requirements — CC6.1 Compliant Guide | PassGeni",
    metaDescription: "SOC 2 CC6.1 password requirements for SaaS companies. What auditors look for, what documentation you need, and how to implement compliant controls.",
    excerpt:         "What SOC 2 auditors actually check when it comes to password controls, and how to ensure CC6.1 compliance without over-engineering.",
    tier:            1,
    badge:           "SOC 2",
    badgeColor:      "#ce93d8",
    publishedAt:     "2025-02-01",
    updatedAt:       "2025-02-01",
    readTime:        9,
    faq: [
      { q: "What does SOC 2 CC6.1 require for passwords?", a: "CC6.1 requires logical access controls, including strong authentication. Auditors typically expect minimum 16 characters, complexity, MFA for privileged access, and a documented policy." },
,
      { q: "What does SOC 2 CC6.1 require for passwords?", a: "CC6.1 requires logical access security including strong authentication controls. Auditors typically expect: minimum 16 characters, complexity requirements, MFA for privileged access, documented password policy, and breach-aware credential management." },
      { q: "What is the minimum password length for SOC 2?", a: "SOC 2 doesn't specify an exact minimum — it requires controls 'appropriate to the risk.' In practice, auditors expect 16+ characters for CC6.1 compliance, especially for admin accounts. PassGeni's SOC 2 preset enforces this automatically." },
      { q: "Is MFA required for SOC 2 Type II certification?", a: "MFA is not explicitly required by the SOC 2 Trust Services Criteria, but its absence is increasingly cited by auditors as a control gap under CC6.1. Most organisations pursuing SOC 2 Type II implement MFA for all internal systems as a matter of course." },
      { q: "How does SOC 2 define 'appropriate' password security?", a: "SOC 2 auditors evaluate whether controls are appropriate to the entity's risk profile. For a SaaS company handling sensitive customer data, appropriate typically means 16+ character passwords, MFA, a written policy, regular access reviews, and breach credential monitoring." },
      { q: "Does SOC 2 require a written password policy?", a: "Yes — CC1.4 requires documented policies and CC6.1 requires logical access controls to be formalised. Your password policy must be documented, approved, communicated to all relevant personnel, and reviewed periodically. Use PassGeni's Policy Generator for a SOC 2-aligned template." },
      { q: "How often should passwords be rotated for SOC 2?", a: "SOC 2 doesn't mandate rotation frequency. Following NIST 800-63B (industry standard), rotate only upon suspected compromise. What auditors focus on instead: MFA, strong generation, access reviews, and breach monitoring — not rotation frequency." },
      { q: "Can I use PassGeni to demonstrate SOC 2 compliance?", a: "PassGeni's SOC 2 preset enforces the password strength controls auditors expect under CC6.1. The Policy Generator creates a written policy you can include in your SOC 2 evidence package. For API-driven onboarding flows, the Team API provides programmatic compliance enforcement with audit trail capability." },
      { q: "What is the difference between SOC 2 Type I and Type II for passwords?", a: "SOC 2 Type I assesses whether controls are suitably designed at a point in time. Type II assesses whether they operated effectively over a period (typically 6-12 months). For passwords, Type II requires evidence that your password controls were consistently applied — logs, policy adherence records, and access reviews." },
      { q: "Do subprocessors need SOC 2 compliant passwords?", a: "CC9.2 requires organisations to assess vendor controls. If your subprocessors access your systems or customer data, their password and authentication practices are in scope. Request their SOC 2 reports or equivalent evidence. Ensure their API access uses compliant credentials." }
    ],
  },
  {
    slug:            "iso-27001-password-requirements",
    title:           "ISO 27001 Password Requirements: Annex A.9 Explained",
    metaTitle:       "ISO 27001 Password Requirements — Annex A.9 Guide | PassGeni",
    metaDescription: "ISO 27001:2022 Annex A.9 password requirements. What the standard requires, what it recommends, and how to implement compliant access controls.",
    excerpt:         "ISO 27001:2022 Annex A.9 covers access control and password management. Here is exactly what it requires and how to implement it.",
    tier:            1,
    badge:           "ISO 27001",
    badgeColor:      "#80cbc4",
    publishedAt:     "2025-02-10",
    updatedAt:       "2025-02-10",
    readTime:        11,
    faq: [
      { q: "What are the ISO 27001 password requirements?", a: "ISO 27001 Annex A.9 requires a minimum 14-character password, enforced complexity (uppercase, lowercase, numbers, symbols), no password reuse within the last 12 passwords, and MFA for privileged access. Passwords must be changed immediately upon compromise." },
      { q: "Does ISO 27001 specify a minimum password length?", a: "ISO 27001 Annex A.9 guidance recommends a minimum of 14 characters for general accounts and 16+ characters for privileged/admin accounts. These are minimum thresholds — longer passwords are always acceptable." },
      { q: "Is MFA required for ISO 27001 certification?", a: "ISO 27001 strongly recommends MFA for privileged access and remote access. Auditors increasingly expect MFA for all administrative accounts and any access to critical business systems as part of Annex A.9 controls." },
      { q: "How does ISO 27001 handle service account passwords?", a: "Service account passwords under ISO 27001 must meet the same minimum length and complexity requirements as user accounts, with the addition of stricter rotation policies (typically quarterly) and storage in a privileged access management (PAM) system." },
      { q: "Can passphrases be used for ISO 27001 compliance?", a: "Yes. ISO 27001 does not prohibit passphrases. A 4-5 word passphrase typically exceeds the 14-character minimum and provides sufficient entropy. NIST 800-63B recommendations are compatible with ISO 27001 Annex A.9 requirements." },
      { q: "How often must passwords be changed under ISO 27001?", a: "ISO 27001 does not mandate periodic rotation. Following NIST 800-63B guidance, passwords should only be changed when there is evidence of compromise. Mandatory periodic rotation is no longer considered best practice and is explicitly discouraged in current NIST guidance." },
      { q: "What password storage requirements does ISO 27001 impose?", a: "ISO 27001 requires passwords to be stored using strong one-way hashing with salt. Acceptable algorithms include bcrypt, Argon2id, and scrypt. MD5, SHA-1, and unsalted hashes are not acceptable. Plaintext storage is strictly prohibited." },
      { q: "Does ISO 27001 require a written password policy?", a: "Yes. ISO 27001 Annex A.9 requires documented access control policies including password requirements. The written policy must be approved by management, communicated to all users, and reviewed at defined intervals." },
      { q: "What is the difference between ISO 27001 and SOC 2 password requirements?", a: "ISO 27001 is an internationally recognised standard with certification by accredited audit bodies, requiring 14-character minimum passwords. SOC 2 is a US-focused attestation framework with more flexible requirements (auditor discretion), typically expecting 16-character minimums for CC6.1 compliance." },
      { q: "How can PassGeni help with ISO 27001 compliance?", a: "PassGeni's ISO 27001 compliance preset automatically enforces the 14-character minimum, required character types, and complexity rules. The Policy Generator tool can produce a written password policy meeting Annex A.9 documentation requirements in minutes." }
    ],
  },
  {
    slug:            "nist-800-63b-password-guidelines",
    title:           "NIST SP 800-63B Password Guidelines: The Complete Summary",
    metaTitle:       "NIST SP 800-63B Password Guidelines — Plain English Summary | PassGeni",
    metaDescription: "NIST SP 800-63B rewrote the rules on passwords. No mandatory rotation. No complexity requirements. Length over complexity. Full plain-English guide.",
    excerpt:         "NIST Special Publication 800-63B changed everything we thought we knew about password requirements. Here is what it actually says in plain English.",
    tier:            1,
    badge:           "NIST",
    badgeColor:      "#a5d6a7",
    publishedAt:     "2025-02-15",
    updatedAt:       "2025-02-15",
    readTime:        14,
    faq: [
      { q: "Does NIST require password rotation?", a: "No. NIST SP 800-63B explicitly advises against mandatory periodic rotation unless there is evidence of compromise. Forced rotation encourages predictable patterns like 'Password1' to 'Password2'." },
      { q: "Does NIST require complexity (uppercase, symbols)?", a: "No. NIST recommends against mandatory complexity rules. Instead, it recommends checking passwords against known breach lists and encouraging length." },
,
      { q: "What are the key NIST 800-63B password requirements?", a: "NIST 800-63B requires: minimum 8 characters (64+ character maximum recommended), check against known-breached credential lists, allow all printable ASCII and Unicode, no mandatory complexity rules, no mandatory periodic rotation, no password hints, no knowledge-based authentication." },
      { q: "Does NIST 800-63B require password complexity?", a: "No — NIST 800-63B explicitly discourages mandatory composition rules (uppercase, lowercase, numbers, symbols). The guidance states composition rules 'often make it harder for people to choose strong passwords' and recommends length and breach checking instead." },
      { q: "What does NIST say about password rotation?", a: "NIST 800-63B explicitly advises against mandatory periodic rotation. Passwords should only be changed when there is evidence of compromise. Forced rotation encourages predictable minimal changes (Password1 → Password2) without improving security." },
      { q: "How does NIST 800-63B handle passphrases?", a: "NIST 800-63B supports passphrases and recommends verifiers accept passwords of at least 64 characters (allowing multi-word passphrases with spaces). The guidance explicitly allows spaces and all Unicode characters, making long passphrases fully compliant." },
      { q: "What is the NIST recommendation on breach checking?", a: "NIST 800-63B Section 5.1.1 recommends verifiers check submitted passwords against lists of known-compromised values, including passwords from previous breach corpora. This should happen at registration and password change. PassGeni's breach checker implements this via the k-anonymous HIBP API." },
      { q: "Does NIST 800-63B require MFA?", a: "NIST 800-63B defines authentication assurance levels (AAL1, AAL2, AAL3). AAL2 (required for most sensitive applications) requires MFA. FIDO2 hardware keys achieve AAL3. Single-factor passwords are only appropriate for AAL1 (low-risk applications)." },
      { q: "Is NIST 800-63B mandatory for private companies?", a: "NIST 800-63B is mandatory for US federal government agencies. Private companies are not legally required to follow it, but it is widely adopted as the industry standard for authentication. HIPAA, PCI-DSS, and SOC 2 auditors increasingly reference NIST 800-63B as the technical benchmark for 'reasonable' controls." },
      { q: "What does NIST say about password hints and security questions?", a: "NIST 800-63B explicitly prohibits password hints and knowledge-based authentication (security questions) as verification methods. These are considered weak factors that reduce overall security. Account recovery should use secondary authentication channels, not guessable personal information." }
    ],
  },
];

// ─── TIER 2: PROFESSION-SPECIFIC GUIDES ──────────────────────
export const PROFESSION_GUIDES = [
  {
    slug:            "password-security-for-healthcare-workers",
    title:           "Password Security for Healthcare Workers: HIPAA-Ready Guide",
    metaTitle:       "Password Security for Healthcare Workers — HIPAA Guide | PassGeni",
    metaDescription: "Password security guide for doctors, nurses, and healthcare staff. HIPAA-compliant password practices that are actually usable in a clinical environment.",
    excerpt:         "Healthcare workers face unique password challenges: shared workstations, frequent logins, strict compliance. This guide covers practical, HIPAA-ready approaches.",
    tier:            2,
    badge:           "Healthcare",
    badgeColor:      "#4fc3f7",
    publishedAt:     "2025-03-01",
    updatedAt:       "2025-03-01",
    readTime:        8,
    faq: [
      { q: "What password requirements apply to healthcare workers?", a: "Healthcare workers accessing EHR systems and patient data fall under HIPAA Security Rule requirements. The minimum is 12 characters with complexity, but NIST 800-63B alignment (length over complexity) is increasingly accepted. MFA is required for all remote access and strongly recommended for all patient data access." },
      { q: "Can healthcare workers use passphrases for HIPAA compliance?", a: "Yes. Passphrases are fully HIPAA-compliant and NIST-recommended. A 4-word passphrase (16+ characters) exceeds HIPAA minimum requirements and is significantly more memorable than complex 12-character strings — reducing the likelihood of password reuse or insecure storage." },
      { q: "How should healthcare workers handle shared workstation passwords?", a: "Shared workstation access should use individual credentials with role-based access control, not shared passwords. Most EHR systems support individual logins on shared hardware. Where shared access is technically unavoidable, use the shortest practical session timeout and audit logging to maintain individual accountability." },
      { q: "What is the biggest password security risk for clinical staff?", a: "Credential phishing targeting clinical staff is the leading cause of healthcare data breaches. Attackers send emails mimicking EHR vendor support requesting login credentials. MFA prevents account takeover even when credentials are phished. Hardware security keys (FIDO2) provide complete phishing resistance." },
      { q: "Are automatic password reset policies required in healthcare?", a: "HIPAA does not mandate automatic periodic rotation. The OCR guidance recommends policies 'as deemed appropriate' by the organisation's risk analysis. Following NIST 800-63B, rotation should be required upon compromise evidence, not on a fixed schedule." },
      { q: "How do I generate HIPAA-compliant passwords?", a: "Use PassGeni's HIPAA compliance preset, which automatically enforces 12-character minimum, all character types, and complexity requirements per HHS guidance. The passphrase mode is also HIPAA-compliant and often more practical for clinical staff who must type credentials in clinical environments." },
      { q: "What should healthcare workers do if they suspect their credentials are compromised?", a: "Immediately report to the IT security team or help desk. Under HIPAA, a credential compromise affecting PHI access may trigger breach notification requirements. The affected account should be locked and credentials reset before reactivation. Enable MFA if not already active." },
      { q: "Can healthcare workers write passwords down?", a: "Writing down passwords is generally discouraged because it creates physical exposure risk. The HIPAA Security Rule doesn't explicitly prohibit it, but OCR has cited written password lists as evidence of inadequate safeguards. A password manager is the secure alternative that eliminates the memory burden driving written passwords." },
      { q: "What is the penalty for a healthcare organisation with weak password policies?", a: "HIPAA penalties for inadequate access controls can range from $100 to $50,000 per violation, with annual caps up to $1.9 million per violation category. The OCR has levied significant fines specifically for authentication failures, including cases where shared passwords and no MFA enabled breaches." },
      { q: "How does zero-knowledge password generation help healthcare compliance?", a: "PassGeni's zero-knowledge architecture means generated passwords never touch a server — they can't be logged, breached, or subpoenaed. For healthcare workers, this means the password generation tool itself cannot become a HIPAA liability, unlike cloud-based tools that transmit or store generated credentials." }
    ],
  },
  {
    slug:            "password-security-for-developers",
    title:           "Password Security for Developers: Secrets, Credentials, and APIs",
    metaTitle:       "Password Security for Developers — Secrets Management Guide | PassGeni",
    metaDescription: "Password security for software developers: SSH keys, API credentials, database passwords, secrets management, and personal account security.",
    excerpt:         "Developers manage more credentials than anyone. This guide covers personal account security, API key hygiene, secrets management, and hardcoded credential risks.",
    tier:            2,
    badge:           "Developers",
    badgeColor:      "#C8FF00",
    publishedAt:     "2025-03-05",
    updatedAt:       "2025-03-05",
    readTime:        15,
    faq: [
      { q: "What password security practices should developers follow?", a: "Developers should use a password manager for all credentials, generate unique passwords for every service, enable MFA on all accounts (especially GitHub, AWS, and cloud consoles), and never hardcode credentials in code. Service account passwords should be managed via a secrets manager." },
      { q: "How should API keys be stored securely?", a: "API keys should never be hardcoded in source code. Use environment variables locally (.env files, never committed), CI/CD secret variables for automation, and a secrets manager (HashiCorp Vault, AWS Secrets Manager, Doppler) for production. Store only the SHA-256 hash server-side when issuing keys to users." },
      { q: "What password hashing algorithm should I use in 2025?", a: "Argon2id is the current best practice, winning the Password Hashing Competition and recommended by OWASP. bcrypt remains acceptable. Use a work factor (cost factor) of at least 10 for bcrypt, or memory of 64MB and 3 iterations for Argon2id. Never use MD5, SHA-1, or SHA-256 alone without iteration." },
      { q: "How do I prevent credential stuffing against my application?", a: "Enable MFA, check passwords against the HIBP breach database at registration and login, implement rate limiting per IP (not just per account), use anomaly detection to flag distributed authentication failures, and consider passkey support to eliminate passwords from the authentication flow entirely." },
      { q: "What NIST guidelines apply to software authentication?", a: "NIST 800-63B Digital Identity Guidelines covers verifiers (your authentication system). Key requirements: minimum 8 characters (64+ recommended maximum), check against breached credential lists, no complexity requirements (length is the primary control), no mandatory rotation without evidence of compromise, support all printable ASCII and Unicode." },
      { q: "Should I force password changes on a schedule in my app?", a: "No — NIST 800-63B explicitly discourages mandatory periodic rotation. Force password changes only when credentials appear in breach databases (check via HIBP API) or when a user reports compromise. Forced rotation without cause trains users to make minimal predictable changes." },
      { q: "How do I implement secure password reset flows?", a: "Password reset links should be single-use, expire within 15–30 minutes, and be sent to the registered email (which you don't control, so consider this a weak link). The reset link should not contain the user ID in a guessable format. After reset, invalidate all existing sessions. Never send passwords via email." },
      { q: "What is the minimum password length for a production application?", a: "NIST recommends accepting passwords of at least 8 characters minimum, with no upper limit below 64 characters. In practice, set your minimum at 12 characters for general accounts and 16 for administrative accounts. Use PassGeni's Team API to generate compliant credentials programmatically if building onboarding flows." },
      { q: "How do I scan for accidentally committed secrets in git history?", a: "Use TruffleHog (open source, scans git history with entropy analysis) or GitLeaks for local/CI scanning. GitHub Advanced Security provides automatic push protection and secret scanning for repositories. Add pre-commit hooks using detect-secrets to prevent commits containing high-entropy strings." },
      { q: "Can I use PassGeni's API to generate passwords in my application?", a: "Yes — PassGeni's Team API allows programmatic password generation with compliance preset enforcement. The API generates cryptographically random credentials using server-side CSPRNG, returns them over HTTPS, and supports all compliance presets (HIPAA, PCI-DSS, SOC 2, NIST, ISO 27001, DoD). See the API documentation for integration details." }
    ],
  },
  {
    slug:            "password-security-for-small-business",
    title:           "Password Security for Small Business: A Practical Guide",
    metaTitle:       "Password Security for Small Business — Practical Guide | PassGeni",
    metaDescription: "Password security for small business owners: team password policies, shared accounts, password managers, and affordable compliance without an IT department.",
    excerpt:         "Small businesses are the #1 target for credential-based attacks. This practical guide covers everything a small business owner needs without an IT team.",
    tier:            2,
    badge:           "SMB",
    badgeColor:      "#ffb74d",
    publishedAt:     "2025-03-10",
    updatedAt:       "2025-03-10",
    readTime:        10,
    faq: [
      { q: "What password security does a small business actually need?", a: "Every small business needs: a team password manager (Bitwarden Teams at $3/user/month is the budget option), MFA on email and any financial systems, a written password policy (use PassGeni's Policy Generator), and a process for offboarding employees that includes credential rotation." },
      { q: "What is the cheapest way to implement proper password security?", a: "Bitwarden free tier handles up to a small team with zero cost. For team sharing, Bitwarden Teams is $3/user/month. PassGeni's tools (generator, breach checker, strength checker, policy generator) are all free. The total cost of adequate password security for a 5-person business: under $20/month." },
      { q: "Do small businesses face the same cyber threats as enterprises?", a: "Yes, and often more so. Automated credential stuffing and ransomware attacks don't discriminate by company size — they're volume operations. Small businesses are often easier targets because they lack enterprise security teams. 43% of cyber attacks target small businesses according to Verizon DBIR data." },
      { q: "What should I do when an employee leaves?", a: "On the day they leave: disable their accounts, revoke their password manager access, rotate any credentials they had direct access to (not just shared vaults), and review which systems they could access. Having a shared vault makes this checklist much shorter — you revoke vault access and rotate credentials specifically in their access scope." },
      { q: "Do I need a written password policy for my small business?", a: "If you process payments (PCI-DSS applies), handle health data (HIPAA applies), or have any cyber insurance policy, a written password policy is likely required. Even without regulatory requirements, a written policy removes ambiguity and protects you legally if an incident occurs. Use PassGeni's Policy Generator to create one in minutes." },
      { q: "How do I share passwords with contractors and freelancers?", a: "Use PassGeni's Secure Share tool for one-time credential handoffs — it creates an AES-256 encrypted link that expires after one view. For ongoing access, use a password manager's sharing feature with an expiry date. Never send credentials via email, Slack, or SMS." },
      { q: "What accounts are highest priority for strong passwords?", a: "In order: business email (recovery for everything), banking and accounting software, your website and hosting, payment processors (PayPal, Stripe), any system containing customer data, and your domain registrar. These are the accounts that cause the most damage if compromised." },
      { q: "Should small businesses use passkeys instead of passwords?", a: "Where supported, passkeys are worth enabling — they eliminate phishing risk entirely for those accounts. But passkey support is still inconsistent across business tools. Use strong passwords plus MFA as the baseline, and enable passkeys on any service that supports them." },
      { q: "How do I check if my business credentials have been breached?", a: "Set up free domain monitoring at HaveIBeenPwned.com — you'll receive an email if any address at your domain appears in a breach. Individually check important passwords with PassGeni's Breach Checker. Run periodic audits using PassGeni's Password Audit Tool." },
      { q: "What is cyber insurance and does password security affect my premium?", a: "Cyber insurance covers costs from data breaches, ransomware, and cyber incidents. Insurers increasingly ask about password controls at application time — MFA adoption, password manager use, written policy. Demonstrating strong controls typically reduces premiums and improves coverage terms." }
    ],
  },
  {
    slug:            "password-security-for-lawyers",
    title:           "Password Security for Lawyers: Bar Ethics and Data Protection",
    metaTitle:       "Password Security for Lawyers — Bar Ethics & Cybersecurity | PassGeni",
    metaDescription: "Password security for attorneys and law firms. ABA model rules on cybersecurity, client confidentiality obligations, and practical password practices.",
    excerpt:         "Attorneys have ethical obligations to protect client data. This guide covers what the ABA model rules require and how to implement it practically.",
    tier:            2,
    badge:           "Legal",
    badgeColor:      "#ce93d8",
    publishedAt:     "2025-03-15",
    updatedAt:       "2025-03-15",
    readTime:        9,
    faq: [
      { q: "What password security requirements apply to law firms?", a: "Lawyers have an ethical duty to protect client confidentiality under ABA Model Rule 1.6. Many state bars have issued guidance requiring 'reasonable' technical measures to protect client data. In practice, this means strong unique passwords, MFA on all systems with client data, encrypted storage, and a written security policy." },
      { q: "Is MFA required for law firm compliance?", a: "The ABA and most state bars require 'reasonable' security measures, and MFA is now considered a baseline for 'reasonable' protection of client data. Several state bar ethics opinions explicitly reference MFA as an expected control. Law firms that have breaches without MFA face both professional responsibility exposure and potential bar discipline." },
      { q: "How should lawyers handle client portal credentials?", a: "Client portals containing sensitive legal documents should be protected with strong unique passwords generated by a password manager and MFA. Never share client portal access credentials with paralegals or assistants — configure the portal to grant role-based access to specific staff instead." },
      { q: "What are the risks of a law firm credential breach?", a: "A law firm credential breach can expose privileged attorney-client communications, case strategy documents, settlement negotiations, and financial records. Beyond client harm, the firm faces potential bar discipline, malpractice claims, and regulatory scrutiny (especially if the firm handles corporate, healthcare, or government clients with their own compliance requirements)." },
      { q: "Can law firms use cloud-based password managers?", a: "Yes — zero-knowledge cloud password managers like Bitwarden and 1Password are appropriate for law firms. The zero-knowledge architecture means even a breach of the password manager vendor leaks nothing about your passwords. Verify your chosen manager has independent security audits and meets your jurisdiction's data residency requirements if applicable." },
      { q: "What password policy should a law firm have?", a: "A law firm password policy should require minimum 14 characters (ISO 27001-aligned), unique passwords for every system, a password manager for all staff, MFA on email and client data systems, prohibition on password sharing via insecure channels, and immediate rotation upon suspected compromise. Generate the policy using PassGeni's Policy Generator." },
      { q: "How should legal matter numbers or client names be handled in passwords?", a: "Never include client names, matter numbers, or any client-identifiable information in passwords. This both creates a security risk (social engineering) and could constitute a confidentiality breach if the password is observed. Use generated random credentials with no meaningful components." },
      { q: "What is the ABA guidance on law firm cybersecurity?", a: "ABA Formal Opinion 477R (2017) states that lawyers must use reasonable efforts to prevent inadvertent disclosure of client information, including using secure communication methods and protecting cloud data. ABA Formal Opinion 483 (2018) covers a lawyer's obligations after an electronic intrusion. Both opinions point toward MFA, encryption, and strong authentication as baseline expectations." },
      { q: "How do law firms handle partner departure and credential offboarding?", a: "Partner departures require immediate revocation of all access — email, client portals, billing systems, document management. All credentials the departing partner could access should be rotated. If shared credentials were used (not recommended), every system must be updated. A password manager with vault sharing makes offboarding auditable and complete." },
      { q: "Is a legal-profession passphrase more secure than a complex password?", a: "Yes — a 4-5 word passphrase exceeds the complexity of most password requirements while being genuinely memorable. PassGeni's Legal profession seeding generates passphrases incorporating legal terminology, making them 30% more recognisable to legal professionals without reducing entropy. This matters for passwords that must be typed in court or in client meetings." }
    ],
  },
  {
    slug:            "password-security-for-remote-workers",
    title:           "Password Security for Remote Workers: VPN, Home Networks, and More",
    metaTitle:       "Password Security for Remote Workers — Complete Guide | PassGeni",
    metaDescription: "Password security for remote workers: home network risks, VPN authentication, shared family devices, and maintaining corporate security standards from home.",
    excerpt:         "Remote work introduced new credential risks: home networks, personal devices, public WiFi, and blurred work/personal boundaries. This guide covers all of it.",
    tier:            2,
    badge:           "Remote Work",
    badgeColor:      "#80cbc4",
    publishedAt:     "2025-03-20",
    updatedAt:       "2025-03-20",
    readTime:        11,
    faq: [
      { q: "What password security practices should remote workers follow?", a: "Remote workers should: use a password manager with unique credentials for every account, enable MFA on all work accounts (email, VPN, cloud tools), never work from public WiFi without a VPN, keep home router firmware updated, and follow company policy on approved tools for credential sharing." },
      { q: "Is home WiFi safe enough for remote work?", a: "Home WiFi is significantly less secure than a managed corporate network. Use WPA3 if your router supports it, use a strong unique password for the router admin interface (not the default), keep firmware updated, and enable VPN for any work involving sensitive client or company data. Segregate work devices from IoT/smart home devices on a separate WiFi network." },
      { q: "What should remote workers do about shared devices?", a: "Personal computers used for work should have separate browser profiles for work and personal use, a password manager installed with work credentials in a separate vault, automatic screen lock after 5 minutes of inactivity, and full-disk encryption enabled (FileVault on Mac, BitLocker on Windows)." },
      { q: "How should remote workers share credentials with colleagues?", a: "Never share credentials via Slack, WhatsApp, email, or SMS — all of these leave permanent records. Use a team password manager vault for ongoing shared access. For one-time credential handoffs, use PassGeni's Secure Share tool, which creates an AES-256 encrypted link that expires after one view." },
      { q: "What is the biggest password security risk for remote workers?", a: "Phishing attacks targeting remote workers are the leading threat. Attackers impersonate IT support, VPN providers, and cloud tool vendors to harvest credentials. MFA prevents account takeover even when credentials are phished. FIDO2 hardware keys provide complete phishing resistance for critical accounts." },
      { q: "Does remote work require different passwords than office work?", a: "The passwords themselves don't change, but the access context matters. Remote workers should expect additional authentication challenges (MFA prompts, conditional access policies) when connecting from new locations or devices. This is normal and a security feature, not a bug." },
      { q: "How do I set up a VPN correctly for remote work?", a: "Use your company-provided VPN rather than a consumer VPN service for work access. Enable VPN automatically for work applications (split tunneling). Your VPN credentials should be strong and unique — not the same as any other work account. MFA on VPN access is strongly recommended." },
      { q: "What should I do if I suspect my work credentials were phished?", a: "Immediately notify your IT security team or help desk. Change your password right away even before they respond. If you have MFA enabled, check recent login activity for unauthorised access. If your work email credentials were compromised, change your password manager master password as well (attackers will use email access to reset other accounts)." },
      { q: "How often should remote workers update their passwords?", a: "Following NIST 800-63B guidance, passwords don't need to be changed on a fixed schedule. Change them immediately if you suspect compromise, if your account appears in a breach notification, or if you previously used the same password on a breached site. Use PassGeni's Breach Checker to verify your credentials periodically." },
      { q: "Are passkeys a good option for remote workers?", a: "Passkeys are an excellent option where supported, as they eliminate phishing risk entirely. Many cloud tools (Google, Microsoft, GitHub) now support passkeys. For a remote worker, passkeys on your primary email and work cloud accounts provide significantly stronger protection than passwords plus SMS 2FA." }
    ],
  },
];

// ─── TIER 3: CONCEPT DEPTH GUIDES ────────────────────────────
export const CONCEPT_GUIDES = [
  {
    slug:            "what-is-password-entropy",
    title:           "What Is Password Entropy? A Plain English Explanation",
    metaTitle:       "What Is Password Entropy? Plain English Explanation | PassGeni",
    metaDescription: "Password entropy explained simply: what it is, how it's calculated, what bits of entropy actually means, and why it's the only real measure of password strength.",
    excerpt:         "Entropy is the only honest measure of password strength. Here is exactly what it means, how to calculate it, and why length matters more than complexity.",
    tier:            3,
    badge:           "Concepts",
    badgeColor:      "#64b5f6",
    publishedAt:     "2025-01-10",
    updatedAt:       "2025-01-10",
    readTime:        7,
    faq: [
      { q: "What is password entropy?", a: "Password entropy is a measure of how unpredictable a password is, expressed in bits. Higher entropy means more possible combinations and a harder brute-force attack. Formula: length × log2(character_pool_size)." },
      { q: "How many bits of entropy is enough?", a: "NIST considers 80+ bits sufficient for most applications. For highly sensitive accounts, 100+ bits is recommended. A 16-character random password from a full character set has approximately 105 bits of entropy." },
,
      { q: "What is password entropy?", a: "Password entropy is a measure of how unpredictable a password is, expressed in bits. It is calculated as: E = length × log₂(character pool size). Higher entropy means more possible combinations and harder brute-force attacks. A 20-character random password from the full ASCII set has ~131 bits of entropy." },
      { q: "How many bits of entropy is a secure password?", a: "NIST considers 80+ bits sufficient for most applications. For highly sensitive accounts, 100+ bits is recommended. Post-quantum security requires 128+ bits to maintain 64-bit effective security against Grover's algorithm. PassGeni's default 18-character output provides approximately 118 bits." },
      { q: "How is password entropy calculated?", a: "Entropy formula: E = L × log₂(N), where L is password length and N is the size of the character pool. Example: 20 characters from full printable ASCII (95 chars) = 20 × log₂(95) = 20 × 6.57 = 131.4 bits of entropy." },
      { q: "Does password complexity increase entropy?", a: "Yes — larger character pools increase entropy per character. Switching from lowercase only (26 chars, 4.7 bits/char) to full ASCII (95 chars, 6.57 bits/char) adds about 1.9 bits per character. But length has a larger effect: each added character multiplies possible combinations by the full pool size." },
      { q: "What is the entropy of a passphrase?", a: "A 4-word Diceware passphrase from a 7,776-word list has entropy of 4 × log₂(7776) = 51.7 bits. A 5-word passphrase gives 64.6 bits, 6 words gives 77.5 bits. These assume random word selection — user-chosen words have significantly lower effective entropy." },
      { q: "Why doesn't high entropy guarantee security?", a: "Entropy calculation assumes truly random generation. Human-created passwords have much lower effective entropy because they follow predictable patterns. 'Summer2024!' technically uses a 95-character pool but has near-zero effective entropy because it's in cracking dictionaries. Use a cryptographic generator like PassGeni." },
      { q: "What is the difference between entropy and crack time?", a: "Entropy measures theoretical unpredictability; crack time estimates how long a specific attack would take. Crack time depends on entropy AND hashing algorithm. A 50-bit entropy password takes seconds to crack if stored as MD5, but thousands of years if stored as Argon2id. PassGeni's Strength Checker shows both." },
      { q: "How does PassGeni calculate entropy?", a: "PassGeni uses the standard formula E = L × log₂(N) where N is the actual character pool size used in generation. For a password with symbols, numbers, upper and lowercase, N = 95. The entropy display in the Strength Checker reflects cryptographic randomness — not the statistical properties of the specific password output." }
    ],
  },
  {
    slug:            "passphrase-vs-password",
    title:           "Passphrase vs Password: Which Is Actually More Secure?",
    metaTitle:       "Passphrase vs Password — Which Is More Secure? | PassGeni",
    metaDescription: "Passphrase vs password: a direct comparison of entropy, memorability, and security. NIST now recommends passphrases. Here is why, with the math.",
    excerpt:         "NIST Special Publication 800-63B recommends passphrases over complex short passwords. Here is the entropy math that explains why 'correct-horse-battery-staple' beats 'P@ssw0rd'.",
    tier:            3,
    badge:           "Concepts",
    badgeColor:      "#81c784",
    publishedAt:     "2025-01-12",
    updatedAt:       "2025-01-12",
    readTime:        8,
    faq: [
      { q: "Are passphrases more secure than passwords?", a: "Passphrases are more secure than typical short complex passwords but can be less secure than very long random passwords. A 4-word passphrase from a 7,776-word wordlist gives ~51 bits of entropy. A 20-character random password from full ASCII gives ~130 bits. For memorised credentials, passphrases win; for stored credentials, random passwords win on entropy." },
      { q: "What does NIST say about passphrases vs passwords?", a: "NIST Special Publication 800-63B recommends length as the primary password quality metric and explicitly supports passphrases. It discourages mandatory complexity rules that produce predictable patterns. NIST recommends accepting any password of 8+ characters and allows passphrases with spaces — maximums should be at least 64 characters." },
      { q: "How many words should a passphrase have?", a: "4 words gives approximately 51 bits of entropy (from a 7,776-word Diceware list), which NIST considers sufficient for most uses. 5 words gives ~62.5 bits. 6 words gives ~77.5 bits, which exceeds most high-security thresholds. For a password manager master password, 6 words is a practical recommendation." },
      { q: "Can I use any words in a passphrase?", a: "For maximum security, passphrase words should be randomly selected from a large wordlist — not chosen by the user. Human-chosen words cluster on predictable patterns (common words, favourite things, pop culture references). PassGeni's passphrase mode uses cryptographic randomness to select from a curated word pool, preventing this bias." },
      { q: "Do passphrases meet corporate password complexity requirements?", a: "Often not automatically — many corporate systems enforce complexity rules (uppercase + number + symbol) that passphrases don't satisfy by default. This is a policy deficiency, not a security deficiency. Organizations should update their password policies to allow passphrases as a NIST-recommended alternative. A passphrase with a capitalised first word and a number appended satisfies most systems." },
      { q: "What is the entropy of a 4-word passphrase?", a: "From a 7,776-word Diceware wordlist (the standard): 4 words = 4 × log2(7776) = 4 × 12.92 = 51.7 bits of entropy. This assumes words are randomly selected. User-chosen words have significantly lower entropy due to predictable selection patterns." },
      { q: "Can passphrases be cracked by dictionary attacks?", a: "Multi-word passphrase attacks (trying combinations of dictionary words) are used by sophisticated attackers. Against 4 randomly-chosen words from a large wordlist, this attack is computationally infeasible — there are too many combinations. Against user-chosen words from common themes, it's more practical, which is why random selection matters." },
      { q: "Which is better for a password manager master password — passphrase or password?", a: "A passphrase is better for a password manager master password because it must be memorised and typed, not autofilled. A 5-6 word random passphrase provides excellent entropy (60-77 bits) while being genuinely typeable under pressure. A 20-character random password is more secure on paper but effectively impossible to reliably type without errors." },
      { q: "Do passphrases work for all types of accounts?", a: "Most modern authentication systems accept passphrases (they're just longer passwords). Exceptions: some legacy systems have maximum length limits of 16 or 20 characters, which a multi-word passphrase may exceed. Also, some systems reject spaces in passwords — using a separator like hyphens or dots usually works around this." },
      { q: "How does PassGeni generate passphrases?", a: "PassGeni's passphrase tab uses crypto.getRandomValues() to randomly select words from a curated word pool seeded with profession-relevant vocabulary. Selection is cryptographically random — no human pattern bias. The profession seeding makes individual words more recognisable to the user without reducing the entropy of the word selection process." }
    ],
  },
  {
    slug:            "what-is-zero-knowledge-architecture",
    title:           "What Is Zero-Knowledge Architecture? Password Security Explained",
    metaTitle:       "Zero-Knowledge Architecture Explained — Password Security | PassGeni",
    metaDescription: "Zero-knowledge architecture means a service provider literally cannot access your data. How it works, how to verify it, and why it matters for password security.",
    excerpt:         "Zero-knowledge is not a marketing claim — it is a specific technical architecture. Here is how it works, how to verify it, and why PassGeni is genuinely zero-knowledge.",
    tier:            3,
    badge:           "Concepts",
    badgeColor:      "#ce93d8",
    publishedAt:     "2025-01-18",
    updatedAt:       "2025-01-18",
    readTime:        9,
    faq: [
      { q: "What is zero-knowledge architecture?", a: "Zero-knowledge architecture means the service provider is architecturally incapable of accessing your data — not just policy-bound not to. In a zero-knowledge password manager, your vault is encrypted on your device before it reaches the server. The server stores only ciphertext it cannot decrypt." },
      { q: "How is zero-knowledge different from end-to-end encryption?", a: "Zero-knowledge and end-to-end encryption are related but distinct. E2E encryption ensures data is encrypted in transit and decrypted only at endpoints. Zero-knowledge goes further: the service provider cannot decrypt your data even if compelled to, because they never have the decryption key. PassGeni's approach is stronger than E2E because no data is transmitted at all." },
      { q: "How can you verify a tool is truly zero-knowledge?", a: "Open your browser's DevTools Network tab and observe what's transmitted while generating a password. A truly zero-knowledge tool transmits nothing to a server. You can also review open-source code (if available) or independent security audits to verify the architecture claims. PassGeni transmits zero data during generation — verifiable in 30 seconds." },
      { q: "Does zero-knowledge mean my data is safe if the company is hacked?", a: "Yes, for properly implemented zero-knowledge architecture. If a zero-knowledge service is breached, attackers obtain only encrypted ciphertext that is mathematically infeasible to decrypt without the key you hold. This is why zero-knowledge password managers can be breached without customers losing their passwords — as happened with the LastPass breach, where only customer vault ciphertext was stolen." },
      { q: "What is the difference between zero-knowledge and zero-trust?", a: "Zero-knowledge is a cryptographic property: the provider cannot access your data. Zero-trust is a network security model: assume no user, device, or network segment is inherently trusted, and verify everything explicitly. They can coexist but address different problems. A zero-trust network may use zero-knowledge tools for credential management." },
      { q: "Is PassGeni zero-knowledge?", a: "Yes — and PassGeni takes it further than most tools. Password generation happens entirely in your browser using JavaScript's crypto.getRandomValues(). No password is ever transmitted to any server. You can verify this by watching the Network tab in DevTools while generating. The free tools are architecturally incapable of knowing your passwords." },
      { q: "Does zero-knowledge apply to the PassGeni Secure Share tool?", a: "Yes. The AES-256 decryption key is embedded in the URL fragment (#), which browsers never transmit to servers. PassGeni's server receives only the encrypted payload — meaningless without the key. Even if PassGeni's servers were fully compromised, the shared secret cannot be recovered from server-side data." },
      { q: "Can zero-knowledge tools comply with legal discovery requests?", a: "A properly implemented zero-knowledge service cannot comply with requests to decrypt user data because it's technically impossible — they don't have the keys. They can provide the encrypted ciphertext, which is useless to investigators without the user's master password. This is an architectural guarantee, not a policy claim." },
      { q: "What are the limitations of zero-knowledge architecture?", a: "Zero-knowledge protects against server-side breaches and provider access, but not against endpoint compromise (if your device is infected with malware, the attacker can read passwords when you decrypt them), phishing, or weak master passwords. Zero-knowledge shifts the attack surface to the endpoint — which is why device security and strong master passwords still matter." },
      { q: "Which password managers use zero-knowledge architecture?", a: "Bitwarden, 1Password, Dashlane, NordPass, and Keeper all use zero-knowledge architecture for vault storage. They encrypt vaults client-side before synchronisation. The key distinction is that PassGeni doesn't store passwords at all — generation is purely local with no vault, making it architecturally simpler and impossible to breach for password data." }
    ],
  },
  {
    slug:            "post-quantum-password-security",
    title:           "Post-Quantum Password Security: What You Need to Know in 2025",
    metaTitle:       "Post-Quantum Password Security 2025 — What to Know | PassGeni",
    metaDescription: "How quantum computers threaten current password security, what NIST's 2024 post-quantum standards mean for credentials, and what to do about it today.",
    excerpt:         "Quantum computers are not yet breaking passwords — but the threat is real and the preparation window is now. Here is what you need to know and do.",
    tier:            3,
    badge:           "Advanced",
    badgeColor:      "#C8FF00",
    publishedAt:     "2025-02-01",
    updatedAt:       "2025-02-01",
    readTime:        13,
    faq: [
      { q: "What is post-quantum password security?", a: "Post-quantum password security refers to generating and storing credentials with sufficient entropy to resist attacks from quantum computers. Quantum computers using Grover's algorithm can theoretically halve the effective bit security of symmetric keys — a 128-bit key becomes effectively 64-bit. This means passwords need higher entropy and longer lengths to maintain equivalent security." },
      { q: "Are quantum computers a threat to passwords right now?", a: "Not yet — current quantum computers (2025) cannot break real-world passwords at any scale. However, credentials generated today may still be in use in 10-15 years when quantum capabilities may be more advanced. Generating post-quantum resistant credentials now costs nothing extra and is a prudent risk-adjusted decision for long-lived secrets." },
      { q: "How does Grover's algorithm threaten password security?", a: "Grover's algorithm is a quantum search algorithm that provides a quadratic speedup over classical brute-force search. Against a password with N bits of entropy, a classical computer needs O(2^N) operations. A quantum computer using Grover's needs O(2^(N/2)) — effectively halving the bit security. A 128-bit entropy password retains only 64 bits of effective security against a quantum attacker." },
      { q: "What does NIST's post-quantum cryptography guidance mean for passwords?", a: "NIST's 2024 Post-Quantum Cryptography standards (FIPS 203, 204, 205) primarily address asymmetric encryption and digital signatures. For symmetric keys and passwords (which use hashing), the guidance is to use at least 256-bit security to maintain 128-bit post-quantum security. For password generation, this means targeting 128+ bits of entropy minimum." },
      { q: "How do I generate post-quantum secure passwords?", a: "Use PassGeni's Post-Quantum mode, which automatically targets 128+ bits of entropy through longer length (minimum 20 characters), expanded character set, and no predictable patterns. This ensures passwords remain secure even against the quadratic speedup Grover's algorithm provides to quantum attackers." },
      { q: "What length password is post-quantum secure?", a: "A password needs sufficient entropy to maintain security after Grover's algorithm halves effective bit strength. A 20+ character random password from the full printable ASCII set (95 characters) provides approximately 131 bits of entropy — equivalent to 65.5 bits against a quantum attacker. This is well above the 64-bit threshold considered computationally infeasible." },
      { q: "Should I change all my passwords for post-quantum security?", a: "For most accounts, current password lengths (16+ characters, random) provide adequate post-quantum security. The accounts worth upgrading to 20+ character passwords now are those with very long expected lifetimes — service accounts, infrastructure credentials, encryption keys, and anything protecting data that must remain confidential for decades." },
      { q: "Does post-quantum mode affect how passwords look?", a: "Post-quantum mode in PassGeni generates longer passwords (20+ characters minimum) with a fuller character set. The passwords look similar to standard generated passwords but are longer and have higher entropy. The visual difference is minor; the security improvement against future quantum attacks is meaningful." },
      { q: "Are passphrases post-quantum secure?", a: "A 6-word Diceware passphrase provides approximately 77.5 bits of entropy — equivalent to about 38 bits against a quantum attacker using Grover's algorithm. This is below recommended post-quantum thresholds. For post-quantum passphrase security, use 8+ words (providing ~103 bits, or 51.5 bits post-quantum)." },
      { q: "What's the timeline for quantum computers threatening current passwords?", a: "Credible estimates suggest cryptographically relevant quantum computers capable of attacking current encryption are 10-20 years away, with significant uncertainty. The 'harvest now, decrypt later' threat model — where adversaries collect encrypted data today to decrypt once quantum computers exist — applies more to asymmetric encryption than to password authentication, which requires real-time access." }
    ],
  },
];

// ─── TIER 4: COMPARISON / INTENT GUIDES ──────────────────────
export const COMPARISON_GUIDES = [
  {
    slug:            "best-password-generator-2025",
    title:           "Best Password Generators in 2025: Ranked and Reviewed",
    metaTitle:       "Best Password Generators 2025 — Ranked & Reviewed | PassGeni",
    metaDescription: "The best password generators of 2025 compared: PassGeni, 1Password, Bitwarden, Dashlane, KeePass, and others. Ranked by security architecture, features, and ease of use.",
    excerpt:         "Not all password generators are built the same. We compare 8 options across security architecture, client-side generation, compliance features, and memorability.",
    tier:            4,
    badge:           "Comparison",
    badgeColor:      "#ffaa00",
    publishedAt:     "2025-03-25",
    updatedAt:       "2025-03-25",
    readTime:        16,
    faq: [
      { q: "What makes a password generator secure?", a: "A secure password generator uses cryptographic randomness (CSPRNG — Cryptographically Secure Pseudo-Random Number Generator), not Math.random() or system time. It should generate from a sufficiently large character pool, produce passwords with verifiable entropy, and ideally run client-side so generated passwords never touch a server." },
      { q: "What is the best free password generator in 2025?", a: "PassGeni is consistently ranked among the best free generators for its combination of client-side generation (zero server contact), FIPS 140-3 entropy via crypto.getRandomValues(), compliance presets (HIPAA, PCI-DSS, SOC 2, NIST, ISO 27001, DoD), profession-aware seeding, and Password DNA Score. All features are free with no account required." },
      { q: "Should I use my password manager's built-in generator or a dedicated tool?", a: "Password manager generators are generally secure and convenient for everyday use. Dedicated tools like PassGeni offer additional value: compliance preset enforcement, entropy analysis, DNA scoring, breach checking, and passphrase generation with NIST 800-63B alignment. For regulated environments, a compliance-aware generator provides better audit documentation." },
      { q: "Are browser-based password generators safe?", a: "Safe if they use crypto.getRandomValues() and run entirely client-side. You can verify by opening DevTools Network tab — a truly client-side generator makes zero network requests during generation. PassGeni generates entirely in your browser. Online generators that transmit passwords to a server for 'storage' or 'history' are fundamentally insecure." },
      { q: "What is the DNA Score in PassGeni?", a: "The Password DNA Score is PassGeni's proprietary quality metric that evaluates passwords across 7 cryptographic checks: entropy level, character class diversity, length threshold, repeat character patterns, sequential character detection, breach database presence (via HIBP), and compliance with selected framework. It produces an A+ to F grade as a human-readable security signal." },
      { q: "What password length should I generate?", a: "For accounts stored in a password manager: 18-20 characters minimum. For accounts you must occasionally type: 14-16 characters or a passphrase. For privileged/admin accounts: 20+ characters or post-quantum mode. PassGeni defaults to 18 characters based on the entropy/practicality tradeoff — above the thresholds for all common compliance frameworks." },
      { q: "Can PassGeni generate HIPAA-compliant passwords?", a: "Yes. PassGeni's HIPAA preset automatically enforces 12-character minimum, required character types (uppercase, lowercase, numbers, symbols), and complexity rules per HHS guidance and NIST 800-63B. Select the HIPAA preset and generate — the resulting passwords meet HIPAA Security Rule requirements for authentication." },
      { q: "Does PassGeni store my generated passwords?", a: "No. PassGeni's generation is entirely client-side using your browser's crypto.getRandomValues() API. No data is sent to any server. Password history is stored in your browser session only — it clears when you close the tab. PassGeni is architecturally incapable of knowing or storing your generated passwords." },
      { q: "What is profession-aware seeding?", a: "PassGeni's AI seeding uses your profession to inject domain-relevant vocabulary into the password generation pool. A doctor might get a medical term embedded in their password; a developer might get a technical term. The cryptographic randomness wrapping it is unchanged — but you're 30% more likely to recognise the password on sight, reducing the need to reset." },
      { q: "Is PassGeni better than 1Password's generator?", a: "1Password's generator is secure and convenient for everyday use within their ecosystem. PassGeni offers advantages for specific use cases: compliance preset enforcement, independent use without a 1Password account, breach checking integration, DNA scoring, and profession-aware seeding. For compliance-heavy environments, PassGeni's preset enforcement provides better audit documentation." }
    ],
  },
  {
    slug:            "passgeni-vs-1password",
    title:           "PassGeni vs 1Password: Which Is Right for You?",
    metaTitle:       "PassGeni vs 1Password — Which Should You Use? | PassGeni",
    metaDescription: "PassGeni vs 1Password: free vs paid, zero-knowledge generation vs encrypted vault, profession-aware passwords vs smart fill. Which is right for your use case?",
    excerpt:         "PassGeni and 1Password serve different needs. PassGeni is a zero-knowledge generator. 1Password is a full password manager. Here is how to choose.",
    tier:            4,
    badge:           "Comparison",
    badgeColor:      "#ffaa00",
    publishedAt:     "2025-04-01",
    updatedAt:       "2025-04-01",
    readTime:        10,
    faq: [
      { q: "What is the difference between PassGeni and 1Password?", a: "PassGeni is a password generator and security toolkit — it creates passwords but doesn't store them. 1Password is a password manager with a built-in generator — it stores, organises, and syncs your credentials across devices. The tools are complementary: use PassGeni to generate NIST-compliant passwords, store them in 1Password." },
      { q: "Does PassGeni replace 1Password?", a: "No. PassGeni generates passwords; 1Password stores and syncs them. You need both functions. Use PassGeni for compliance-aware generation (especially if you need HIPAA, PCI-DSS, or SOC 2 preset enforcement), then save the generated credentials in 1Password or Bitwarden." },
      { q: "Why use PassGeni over 1Password's built-in generator?", a: "1Password's generator is secure but lacks compliance preset enforcement (HIPAA, PCI-DSS, SOC 2, etc.), a Password DNA Score, breach checking integration, profession-aware seeding, and passphrase mode with NIST 800-63B alignment. For teams with compliance requirements, PassGeni's preset enforcement provides better audit documentation." },
      { q: "Is 1Password zero-knowledge?", a: "Yes — 1Password uses a dual-key encryption model (master password + secret key) and zero-knowledge architecture. Your vault is encrypted client-side before syncing to 1Password's servers. 1Password cannot decrypt your vault even if compelled to. PassGeni is even more zero-knowledge — it transmits nothing at all, as generation is purely local." },
      { q: "Is PassGeni free compared to 1Password?", a: "PassGeni's individual tools (generator, breach checker, strength checker, passphrase generator, secure share, WiFi QR, audit, policy generator) are all completely free with no account required. 1Password costs $36/year personal or $60/year families. The Team API is $29/month for teams needing programmatic access." },
      { q: "Can I use PassGeni with 1Password together?", a: "Yes — and this is the recommended workflow. Generate compliant passwords in PassGeni (using the appropriate compliance preset), then save them directly into 1Password's vault. For bulk credential generation, use PassGeni's bulk generator, export as CSV, and import into 1Password." },
      { q: "Which has better compliance support?", a: "PassGeni has more explicit compliance preset enforcement — HIPAA, PCI-DSS v4.0, SOC 2, ISO 27001, NIST 800-63B, and DoD presets that automatically configure password parameters. 1Password's generator doesn't have compliance-specific presets. For regulated industries, PassGeni's compliance output provides better audit evidence." },
      { q: "Does 1Password have a passphrase generator?", a: "Yes — 1Password includes a word-based passphrase generator. PassGeni's passphrase mode adds profession-aware seeding that makes words more recognisable to the user without reducing entropy, along with NIST 800-63B alignment and entropy calculation." },
      { q: "What happens to my PassGeni passwords if the service goes down?", a: "Nothing — because PassGeni never stores them. All generation is client-side. If PassGeni's website is unavailable, you can continue using any passwords previously generated and stored in your password manager. Unlike cloud-dependent tools, PassGeni's core function has zero server dependency." },
      { q: "Is PassGeni secure for enterprise use?", a: "PassGeni's Team API plan is designed for enterprise integration — it offers compliance preset enforcement via REST API, 5,000 calls/day, team dashboard, API key rotation, and priority support. Many compliance teams use the API to generate credentials programmatically during employee onboarding flows." }
    ],
  },
  {
    slug:            "free-vs-paid-password-generators",
    title:           "Free vs Paid Password Generators: What Do You Actually Get?",
    metaTitle:       "Free vs Paid Password Generators — What's the Difference? | PassGeni",
    metaDescription: "What do paid password generators offer that free ones don't? Compliance presets, API access, team management, and audit logging explained.",
    excerpt:         "Most people do not need a paid password generator. But for teams, compliance requirements, and API access, the differences are significant.",
    tier:            4,
    badge:           "Comparison",
    badgeColor:      "#ffaa00",
    publishedAt:     "2025-04-05",
    updatedAt:       "2025-04-05",
    readTime:        8,
    faq: [
      { q: "What is the difference between free and paid password generators?", a: "Free generators typically offer basic random password generation. Paid or premium generators add compliance preset enforcement, team API access, bulk generation, audit logs, dashboard analytics, and integration capabilities. PassGeni offers all free tools at no cost, with the Team API as the paid tier for programmatic access at scale." },
      { q: "Are free password generators secure?", a: "Security depends on implementation, not price. A free tool using crypto.getRandomValues() client-side is more secure than a paid tool transmitting passwords to a server. The key questions: does it use a CSPRNG? Does it run client-side? Can you verify via network inspection? PassGeni satisfies all three and is free." },
      { q: "What do I lose by using a free password generator?", a: "With most free generators: compliance preset enforcement, team management, API access, audit trails, and bulk generation. PassGeni's free tier is unusually complete — it includes compliance presets, passphrase mode, breach checking, strength analysis, DNA score, and bulk generation (up to 10 passwords). API access and team features require the paid Team plan." },
      { q: "Is PassGeni's free tier really free?", a: "Yes — all individual tools are permanently free with no account required, no credit card, no trial period. The generator, passphrase mode, breach checker, strength checker, password audit tool, policy generator, secure share, and WiFi QR generator are all free forever. Only the Team API plan ($29/month) is paid." },
      { q: "What compliance features are free on PassGeni?", a: "All compliance presets — HIPAA, PCI-DSS, SOC 2, ISO 27001, NIST 800-63B, and DoD — are free in the web generator. The Policy Generator tool (which produces a written password policy document) is also free. Only programmatic API access to compliance presets requires the Team plan." },
      { q: "Are paid password managers worth it for individuals?", a: "Bitwarden's free tier is complete for individual use. 1Password's $36/year is worth it if you value polished UX and advanced features. Most individuals don't need to pay for password generation — PassGeni's free generator plus Bitwarden's free vault covers all use cases without cost." },
      { q: "What features should I look for in a password generator?", a: "Client-side generation (verify via network tab), CSPRNG entropy (crypto.getRandomValues()), compliance preset support, entropy/strength display, passphrase mode, breach checking, and no account requirement for basic use. Paid features worth evaluating: team API, bulk generation, audit logs, and CSV export." },
      { q: "Why do some free generators require account creation?", a: "Account requirements for basic generators often exist to collect email addresses for marketing, enable password storage/sync (which creates security risks), or lock features behind registration walls. PassGeni requires no account for any individual tool — accounts are only needed for the Team API plan." },
      { q: "Can free password generators be used for HIPAA or PCI-DSS compliance?", a: "Yes — PassGeni's HIPAA and PCI-DSS presets are free and enforce the correct password parameters for each standard. The generated passwords are fully compliant. For organisations needing audit evidence of programmatic compliance enforcement, the Team API plan provides API access with compliance preset enforcement." },
      { q: "What is the PassGeni Team API and who needs it?", a: "The PassGeni Team API ($29/month) provides REST API access to the password generator with compliance preset enforcement, 5,000 calls/day, 5 team seats, bulk generation up to 500 passwords, CSV export, and a team dashboard. It's designed for development teams, HR systems automating onboarding, or compliance teams enforcing password standards programmatically." }
    ],
  },
];

// ─── ALL GUIDES COMBINED ──────────────────────────────────────
export const ALL_GUIDES = [
  ...COMPLIANCE_GUIDES,
  ...PROFESSION_GUIDES,
  ...CONCEPT_GUIDES,
  ...COMPARISON_GUIDES,
];

// ─── HELPER: find guide by slug ───────────────────────────────
export function getGuideBySlug(slug) {
  return ALL_GUIDES.find((g) => g.slug === slug) || null;
}

// ─── HELPER: get related guides ───────────────────────────────
export function getRelatedGuides(slug, count = 3) {
  const current = getGuideBySlug(slug);
  if (!current) return [];
  return ALL_GUIDES
    .filter((g) => g.slug !== slug && g.tier === current.tier)
    .slice(0, count);
}
