import PageLayout from "../components/layout/PageLayout.js";

const LINK = { color: "#C8FF00", textDecoration: "none" };
const H2   = { fontFamily: "var(--font-heading)", fontWeight: 800, fontSize: "clamp(20px,2.5vw,28px)", color: "#fff", letterSpacing: "-0.02em", marginBottom: 16, marginTop: 48 };
const P    = { fontFamily: "var(--font-body)", fontSize: 16, color: "#bbb", lineHeight: 1.85, marginBottom: 20 };
const LI   = { fontFamily: "var(--font-body)", fontSize: 16, color: "#bbb", lineHeight: 1.85, marginBottom: 10 };

export default function TermsPage() {
  return (
    <PageLayout
      title="Terms of Service — PassGeni"
      description="PassGeni terms of service. Free to use, no account required. Team API plan terms included."
      canonical="https://passgeni.ai/terms"
    >
      <main style={{ maxWidth: 720, margin: "0 auto", padding: "80px var(--page-pad) 120px" }}>
        <div style={{ fontFamily: "var(--font-mono)", fontSize: 10, color: "#555", letterSpacing: "0.14em", textTransform: "uppercase", marginBottom: 16 }}>Legal</div>
        <h1 style={{ fontFamily: "var(--font-heading)", fontWeight: 800, fontSize: "clamp(28px,4vw,48px)", color: "#fff", letterSpacing: "-0.02em", lineHeight: 1.1, marginBottom: 12 }}>Terms of Service</h1>
        <p style={{ fontFamily: "var(--font-mono)", fontSize: 11, color: "#555", marginBottom: 48 }}>Last updated: March 2026 · Effective immediately</p>

        <p style={P}>By using PassGeni ("Service", "we", "us"), you agree to these terms. If you don't agree, don't use the service. These terms are intentionally plain English.</p>

        <h2 style={H2}>The free tools</h2>
        <p style={P}>PassGeni's free tools (password generator, breach checker, strength checker, passphrase generator, secure share, WiFi QR generator, audit tool, policy generator) are free to use for personal and commercial purposes. No account required. No attribution required.</p>

        <h2 style={H2}>Team API plan</h2>
        <p style={P}>The Team plan ($29/month) gives you REST API access for programmatic password generation with compliance presets. You agree to:</p>
        <ul style={{ paddingLeft: 24, marginBottom: 24 }}>
          {["Use the API only for lawful purposes", "Not resell or white-label the API without a separate agreement", "Protect your API key — you're responsible for all usage on your key", "Stay within the 5,000 calls/day limit on the Team plan", "Not use the API to generate passwords for malicious software, credential stuffing, or unauthorized access"].map(item => <li key={item} style={LI}>{item}</li>)}
        </ul>

        <h2 style={H2}>No warranty</h2>
        <p style={P}>PassGeni is provided "as is" without warranty of any kind. We don't guarantee that passwords generated by PassGeni will meet every compliance requirement in every jurisdiction — compliance requirements change and you should verify requirements with your own counsel or auditor.</p>

        <h2 style={H2}>Limitation of liability</h2>
        <p style={P}>To the fullest extent permitted by law, PassGeni's total liability for any claim arising from your use of the service is limited to the amount you paid us in the 12 months before the claim. For free users, this means zero.</p>

        <h2 style={H2}>Refunds</h2>
        <p style={P}>Team plan subscriptions can be cancelled any time. We offer a 14-day refund for new subscribers if you've used fewer than 500 API calls. Contact <a href="mailto:billing@passgeni.ai" style={LINK}>billing@passgeni.ai</a>.</p>

        <h2 style={H2}>Acceptable use</h2>
        <p style={P}>Don't use PassGeni for anything illegal, harmful, or designed to compromise the security of others. We reserve the right to terminate API access for abuse without notice.</p>

        <h2 style={H2}>Changes</h2>
        <p style={P}>We may update these terms. We'll notify Team plan users by email for material changes. The current version is always at <a href="/terms" style={LINK}>passgeni.ai/terms</a>.</p>

        <h2 style={H2}>Governing law</h2>
        <p style={P}>These terms are governed by the laws of the United States. Disputes shall be resolved by binding arbitration under JAMS rules.</p>

        <h2 style={H2}>Contact</h2>
        <p style={P}>Questions about these terms? Email <a href="mailto:legal@passgeni.ai" style={LINK}>legal@passgeni.ai</a> or visit our <a href="/contact" style={LINK}>contact page</a>.</p>
      </main>
    </PageLayout>
  );
}
